/* Generated by dmlc, do not edit! */

#ifndef T_INLINE_PARAMS_INDEX_STRUCT_H
#define T_INLINE_PARAMS_INDEX_STRUCT_H

typedef struct test test_t;

conf_class_t *_initialize_T_inline_params_index(void);


#endif /* not T_INLINE_PARAMS_INDEX_STRUCT_H */
