/* Generated by dmlc, do not edit! */

#ifndef T_IMMEDIATE_AFTER_BASIC_STRUCT_H
#define T_IMMEDIATE_AFTER_BASIC_STRUCT_H

typedef struct test test_t;

conf_class_t *_initialize_T_immediate_after_basic(void);


#endif /* not T_IMMEDIATE_AFTER_BASIC_STRUCT_H */
