/* Generated by dmlc, do not edit! */

#ifndef T_THROWING_INITIALIZERS_STRUCT_H
#define T_THROWING_INITIALIZERS_STRUCT_H

typedef struct test test_t;

conf_class_t *_initialize_T_throwing_initializers(void);


#endif /* not T_THROWING_INITIALIZERS_STRUCT_H */
