/* Generated by dmlc, do not edit! */

#ifndef T_WDEPRECATED_STRUCT_H
#define T_WDEPRECATED_STRUCT_H

typedef struct test test_t;

conf_class_t *_initialize_T_WDEPRECATED(void);


#endif /* not T_WDEPRECATED_STRUCT_H */
