/* Generated by dmlc, do not edit! */

#ifndef T_CONNECT_NONREQ_INT_STRUCT_H
#define T_CONNECT_NONREQ_INT_STRUCT_H

typedef struct test test_t;

conf_class_t *_initialize_T_connect_nonreq_int(void);


#endif /* not T_CONNECT_NONREQ_INT_STRUCT_H */
