/* Generated by dmlc, do not edit! */

#ifndef T_SHARED_LOGS_ON_DEVICE_ENABLED_STRUCT_H
#define T_SHARED_LOGS_ON_DEVICE_ENABLED_STRUCT_H

typedef struct test test_t;

conf_class_t *_initialize_T_shared_logs_on_device_enabled(void);


#endif /* not T_SHARED_LOGS_ON_DEVICE_ENABLED_STRUCT_H */
