/* Generated by dmlc, do not edit! */

#ifndef T_EASSIGN_15_STRUCT_H
#define T_EASSIGN_15_STRUCT_H

typedef struct eassign eassign_t;

conf_class_t *_initialize_T_EASSIGN_15(void);


#endif /* not T_EASSIGN_15_STRUCT_H */
