/* Generated by dmlc, do not edit! */

#ifndef T_DEAD_METHODS_STRUCT_H
#define T_DEAD_METHODS_STRUCT_H

typedef struct test test_t;

conf_class_t *_initialize_T_dead_methods(void);

extern void  exported(conf_object_t *_obj);

#endif /* not T_DEAD_METHODS_STRUCT_H */
