/* Generated by dmlc, do not edit! */

#ifndef T_SLICE_BOOL_STRUCT_H
#define T_SLICE_BOOL_STRUCT_H

typedef struct test test_t;

conf_class_t *_initialize_T_slice_bool(void);


#endif /* not T_SLICE_BOOL_STRUCT_H */
