/* Generated by dmlc, do not edit! */

#ifndef T_ATTRIBUTE_ARRAY_2_STRUCT_H
#define T_ATTRIBUTE_ARRAY_2_STRUCT_H

typedef struct test test_t;

conf_class_t *_initialize_T_attribute_array_2(void);


#endif /* not T_ATTRIBUTE_ARRAY_2_STRUCT_H */
