/* Generated by dmlc, do not edit! */

#ifndef T_STRINGLIT_STRUCT_H
#define T_STRINGLIT_STRUCT_H

typedef struct test test_t;

conf_class_t *_initialize_T_stringlit(void);


#endif /* not T_STRINGLIT_STRUCT_H */
