/* Generated by dmlc, do not edit! */

#ifndef T_IMPORT_REL_STRUCT_H
#define T_IMPORT_REL_STRUCT_H

typedef struct test test_t;

conf_class_t *_initialize_T_import_rel(void);


#endif /* not T_IMPORT_REL_STRUCT_H */
