/* Generated by dmlc, do not edit! */

#ifndef T_INVOKE_STRUCT_H
#define T_INVOKE_STRUCT_H

typedef struct test test_t;

conf_class_t *_initialize_T_invoke(void);


#endif /* not T_INVOKE_STRUCT_H */
