/* Generated by dmlc, do not edit! */

#ifndef T_CANCELLATION_STRUCT_H
#define T_CANCELLATION_STRUCT_H

typedef struct test test_t;

conf_class_t *_initialize_T_cancellation(void);


#endif /* not T_CANCELLATION_STRUCT_H */
