/* Generated by dmlc, do not edit! */

#ifndef T_CONSTPROP_STRUCT_H
#define T_CONSTPROP_STRUCT_H

typedef struct test test_t;

conf_class_t *_initialize_T_constprop(void);


#endif /* not T_CONSTPROP_STRUCT_H */
