/* Generated by dmlc, do not edit! */

#ifndef T_NOLINEBREAK_1_STRUCT_H
#define T_NOLINEBREAK_1_STRUCT_H

typedef struct test test_t;

conf_class_t *_initialize_T_nolinebreak_1(void);


#endif /* not T_NOLINEBREAK_1_STRUCT_H */
