/* Generated by dmlc, do not edit! */

#ifndef T_DIAMOND_OVERRIDE_STRUCT_H
#define T_DIAMOND_OVERRIDE_STRUCT_H

typedef struct test test_t;

conf_class_t *_initialize_T_diamond_override(void);


#endif /* not T_DIAMOND_OVERRIDE_STRUCT_H */
