/* Generated by dmlc, do not edit! */

#ifndef T_LENIENT_TYPECHECKING_ENABLED_STRUCT_H
#define T_LENIENT_TYPECHECKING_ENABLED_STRUCT_H

typedef struct test test_t;

conf_class_t *_initialize_T_lenient_typechecking_enabled(void);


#endif /* not T_LENIENT_TYPECHECKING_ENABLED_STRUCT_H */
