/* Generated by dmlc, do not edit! */

#ifndef T_STATIC_INDEXED_STRUCT_H
#define T_STATIC_INDEXED_STRUCT_H

typedef struct test test_t;

conf_class_t *_initialize_T_static_indexed(void);


#endif /* not T_STATIC_INDEXED_STRUCT_H */
