/* Generated by dmlc, do not edit! */

#ifndef T_PARAM_EXPR_STRUCT_H
#define T_PARAM_EXPR_STRUCT_H

typedef struct test test_t;

conf_class_t *_initialize_T_param_expr(void);


#endif /* not T_PARAM_EXPR_STRUCT_H */
