/* Generated by dmlc, do not edit! */

#ifndef T_REGISTERS_STRUCT_H
#define T_REGISTERS_STRUCT_H

typedef struct test test_t;

conf_class_t *_initialize_T_registers(void);


#endif /* not T_REGISTERS_STRUCT_H */
