/* Generated by dmlc, do not edit! */

#ifndef T_HEADER_COMMENT_4_STRUCT_H
#define T_HEADER_COMMENT_4_STRUCT_H

typedef struct test test_t;

conf_class_t *_initialize_T_header_comment_4(void);


#endif /* not T_HEADER_COMMENT_4_STRUCT_H */
