/* Generated by dmlc, do not edit! */

#ifndef T_BITFIELDS_MEMBER_SIGN_STRUCT_H
#define T_BITFIELDS_MEMBER_SIGN_STRUCT_H

typedef struct test test_t;

conf_class_t *_initialize_T_bitfields_member_sign(void);


#endif /* not T_BITFIELDS_MEMBER_SIGN_STRUCT_H */
