/* Generated by dmlc, do not edit! */

#ifndef T_PORTING_FAIL_STRUCT_H
#define T_PORTING_FAIL_STRUCT_H

typedef struct test test_t;

conf_class_t *_initialize_T_porting_fail(void);


#endif /* not T_PORTING_FAIL_STRUCT_H */
