/* Generated by dmlc, do not edit! */

#ifndef T_REMOVE_STRUCT_H
#define T_REMOVE_STRUCT_H

typedef struct test test_t;

conf_class_t *_initialize_T_remove(void);


#endif /* not T_REMOVE_STRUCT_H */
