/* Generated by dmlc, do not edit! */

#ifndef T_IFACE_DECL_1_STRUCT_H
#define T_IFACE_DECL_1_STRUCT_H

typedef struct test test_t;

conf_class_t *_initialize_T_iface_decl_1(void);


#endif /* not T_IFACE_DECL_1_STRUCT_H */
