/* Generated by dmlc, do not edit! */

#ifndef T_ARRAY_SET_5_STRUCT_H
#define T_ARRAY_SET_5_STRUCT_H

typedef struct test test_t;

conf_class_t *_initialize_T_array_set_5(void);


#endif /* not T_ARRAY_SET_5_STRUCT_H */
