/* Generated by dmlc, do not edit! */

#ifndef T_PTR_INCDEC_STRUCT_H
#define T_PTR_INCDEC_STRUCT_H

typedef struct test test_t;

conf_class_t *_initialize_T_ptr_incdec(void);


#endif /* not T_PTR_INCDEC_STRUCT_H */
