/* Generated by dmlc, do not edit! */

#ifndef T_METHODS_5_STRUCT_H
#define T_METHODS_5_STRUCT_H

typedef struct test test_t;

conf_class_t *_initialize_T_methods_5(void);


#endif /* not T_METHODS_5_STRUCT_H */
