/* Generated by dmlc, do not edit! */

#ifndef T_ISTEMPLATE_STRUCT_H
#define T_ISTEMPLATE_STRUCT_H

typedef struct test test_t;

conf_class_t *_initialize_T_istemplate(void);


#endif /* not T_ISTEMPLATE_STRUCT_H */
