/* Generated by dmlc, do not edit! */

#ifndef T_LOCALS_1_H
#define T_LOCALS_1_H

#define DML_PREFIX(x) test_##x

#define DML_LEGACY_ATTRS 1
#define DMLDIR_SWABBER_H "C:\\Users\\nagen\\simics-projects\\my-intel-simics-project-1\\win64\\bin\\dml\\api\\6\\1.2\\simics\\util\\swabber.h"
#line 16 "C:\\Users\\nagen\\simics-projects\\my-intel-simics-project-1\\win64\\bin\\dml\\api\\6\\1.2\\simics\\util\\swabber.dml"

#include <simics\util\swabber.h>
#line 14 "C:\\Users\\nagen\\simics-projects\\my-intel-simics-project-1\\logs\\test\\win64\\modules\\dmlc\\test\\scratch\\1.2\\trivial\\locals_1\\T_locals_1.h"
#undef DMLDIR_SWABBER_H

#define DMLDIR_FRAGS_H "C:\\Users\\nagen\\simics-projects\\my-intel-simics-project-1\\win64\\bin\\dml\\api\\6\\1.2\\simics\\util\\frags.h"
#line 16 "C:\\Users\\nagen\\simics-projects\\my-intel-simics-project-1\\win64\\bin\\dml\\api\\6\\1.2\\simics\\util\\frags.dml"

#include <simics\util\frags.h>
#line 21 "C:\\Users\\nagen\\simics-projects\\my-intel-simics-project-1\\logs\\test\\win64\\modules\\dmlc\\test\\scratch\\1.2\\trivial\\locals_1\\T_locals_1.h"
#undef DMLDIR_FRAGS_H

#define DMLDIR_CALLBACKS_H "C:\\Users\\nagen\\simics-projects\\my-intel-simics-project-1\\win64\\bin\\dml\\api\\6\\1.2\\simics\\base\\callbacks.h"
#line 16 "C:\\Users\\nagen\\simics-projects\\my-intel-simics-project-1\\win64\\bin\\dml\\api\\6\\1.2\\simics\\base\\callbacks.dml"

#include <simics\base\callbacks.h>
#line 28 "C:\\Users\\nagen\\simics-projects\\my-intel-simics-project-1\\logs\\test\\win64\\modules\\dmlc\\test\\scratch\\1.2\\trivial\\locals_1\\T_locals_1.h"
#undef DMLDIR_CALLBACKS_H

#define DMLDIR_DURATION_H "C:\\Users\\nagen\\simics-projects\\my-intel-simics-project-1\\win64\\bin\\dml\\api\\6\\1.2\\simics\\base\\duration.h"
#line 16 "C:\\Users\\nagen\\simics-projects\\my-intel-simics-project-1\\win64\\bin\\dml\\api\\6\\1.2\\simics\\base\\duration.dml"

#include <simics\base\duration.h>
#line 35 "C:\\Users\\nagen\\simics-projects\\my-intel-simics-project-1\\logs\\test\\win64\\modules\\dmlc\\test\\scratch\\1.2\\trivial\\locals_1\\T_locals_1.h"
#undef DMLDIR_DURATION_H

#define DMLDIR_BIGTIME_H "C:\\Users\\nagen\\simics-projects\\my-intel-simics-project-1\\win64\\bin\\dml\\api\\6\\1.2\\simics\\base\\bigtime.h"
#line 16 "C:\\Users\\nagen\\simics-projects\\my-intel-simics-project-1\\win64\\bin\\dml\\api\\6\\1.2\\simics\\base\\bigtime.dml"

#include <simics\base\bigtime.h>
#line 42 "C:\\Users\\nagen\\simics-projects\\my-intel-simics-project-1\\logs\\test\\win64\\modules\\dmlc\\test\\scratch\\1.2\\trivial\\locals_1\\T_locals_1.h"
#undef DMLDIR_BIGTIME_H

#define DMLDIR_LOCAL_TIME_H "C:\\Users\\nagen\\simics-projects\\my-intel-simics-project-1\\win64\\bin\\dml\\api\\6\\1.2\\simics\\base\\local-time.h"
#line 16 "C:\\Users\\nagen\\simics-projects\\my-intel-simics-project-1\\win64\\bin\\dml\\api\\6\\1.2\\simics\\base\\local-time.dml"

#include <simics\base\local-time.h>
#line 49 "C:\\Users\\nagen\\simics-projects\\my-intel-simics-project-1\\logs\\test\\win64\\modules\\dmlc\\test\\scratch\\1.2\\trivial\\locals_1\\T_locals_1.h"
#undef DMLDIR_LOCAL_TIME_H

#define DMLDIR_CYCLE_H "C:\\Users\\nagen\\simics-projects\\my-intel-simics-project-1\\win64\\bin\\dml\\api\\6\\1.2\\simics\\model-iface\\cycle.h"
#line 16 "C:\\Users\\nagen\\simics-projects\\my-intel-simics-project-1\\win64\\bin\\dml\\api\\6\\1.2\\simics\\model-iface\\cycle.dml"

#include <simics\model-iface\cycle.h>
#line 56 "C:\\Users\\nagen\\simics-projects\\my-intel-simics-project-1\\logs\\test\\win64\\modules\\dmlc\\test\\scratch\\1.2\\trivial\\locals_1\\T_locals_1.h"
#undef DMLDIR_CYCLE_H

#define DMLDIR_CLOCK_H "C:\\Users\\nagen\\simics-projects\\my-intel-simics-project-1\\win64\\bin\\dml\\api\\6\\1.2\\simics\\base\\clock.h"
#line 16 "C:\\Users\\nagen\\simics-projects\\my-intel-simics-project-1\\win64\\bin\\dml\\api\\6\\1.2\\simics\\base\\clock.dml"

#include <simics\base\clock.h>
#line 63 "C:\\Users\\nagen\\simics-projects\\my-intel-simics-project-1\\logs\\test\\win64\\modules\\dmlc\\test\\scratch\\1.2\\trivial\\locals_1\\T_locals_1.h"
#undef DMLDIR_CLOCK_H

#define DMLDIR_LOG_H "C:\\Users\\nagen\\simics-projects\\my-intel-simics-project-1\\win64\\bin\\dml\\api\\6\\1.2\\simics\\base\\log.h"
#line 16 "C:\\Users\\nagen\\simics-projects\\my-intel-simics-project-1\\win64\\bin\\dml\\api\\6\\1.2\\simics\\base\\log.dml"

#include <simics\base\log.h>
#line 70 "C:\\Users\\nagen\\simics-projects\\my-intel-simics-project-1\\logs\\test\\win64\\modules\\dmlc\\test\\scratch\\1.2\\trivial\\locals_1\\T_locals_1.h"
#undef DMLDIR_LOG_H

#define DMLDIR_CONFIGURATION_H "C:\\Users\\nagen\\simics-projects\\my-intel-simics-project-1\\win64\\bin\\dml\\api\\6\\1.2\\simics\\base\\configuration.h"
#line 16 "C:\\Users\\nagen\\simics-projects\\my-intel-simics-project-1\\win64\\bin\\dml\\api\\6\\1.2\\simics\\base\\configuration.dml"

#include <simics\base\configuration.h>
#line 77 "C:\\Users\\nagen\\simics-projects\\my-intel-simics-project-1\\logs\\test\\win64\\modules\\dmlc\\test\\scratch\\1.2\\trivial\\locals_1\\T_locals_1.h"
#undef DMLDIR_CONFIGURATION_H

#define DMLDIR_GLOBAL_NOTIFIER_H "C:\\Users\\nagen\\simics-projects\\my-intel-simics-project-1\\win64\\bin\\dml\\api\\6\\1.2\\simics\\base\\global-notifier.h"
#line 16 "C:\\Users\\nagen\\simics-projects\\my-intel-simics-project-1\\win64\\bin\\dml\\api\\6\\1.2\\simics\\base\\global-notifier.dml"

#include <simics\base\global-notifier.h>
#line 84 "C:\\Users\\nagen\\simics-projects\\my-intel-simics-project-1\\logs\\test\\win64\\modules\\dmlc\\test\\scratch\\1.2\\trivial\\locals_1\\T_locals_1.h"
#undef DMLDIR_GLOBAL_NOTIFIER_H

#define DMLDIR_HAP_PRODUCER_H "C:\\Users\\nagen\\simics-projects\\my-intel-simics-project-1\\win64\\bin\\dml\\api\\6\\1.2\\simics\\base\\hap-producer.h"
#line 16 "C:\\Users\\nagen\\simics-projects\\my-intel-simics-project-1\\win64\\bin\\dml\\api\\6\\1.2\\simics\\base\\hap-producer.dml"

#include <simics\base\hap-producer.h>
#line 91 "C:\\Users\\nagen\\simics-projects\\my-intel-simics-project-1\\logs\\test\\win64\\modules\\dmlc\\test\\scratch\\1.2\\trivial\\locals_1\\T_locals_1.h"
#undef DMLDIR_HAP_PRODUCER_H

#define DMLDIR_TRANSACTION_H "C:\\Users\\nagen\\simics-projects\\my-intel-simics-project-1\\win64\\bin\\dml\\api\\6\\1.2\\simics\\base\\transaction.h"
#line 16 "C:\\Users\\nagen\\simics-projects\\my-intel-simics-project-1\\win64\\bin\\dml\\api\\6\\1.2\\simics\\base\\transaction.dml"

#include <simics\base\transaction.h>
#line 98 "C:\\Users\\nagen\\simics-projects\\my-intel-simics-project-1\\logs\\test\\win64\\modules\\dmlc\\test\\scratch\\1.2\\trivial\\locals_1\\T_locals_1.h"
#undef DMLDIR_TRANSACTION_H

#define DMLDIR_DIRECT_MEMORY_H "C:\\Users\\nagen\\simics-projects\\my-intel-simics-project-1\\win64\\bin\\dml\\api\\6\\1.2\\simics\\base\\direct-memory.h"
#line 16 "C:\\Users\\nagen\\simics-projects\\my-intel-simics-project-1\\win64\\bin\\dml\\api\\6\\1.2\\simics\\base\\direct-memory.dml"

#include <simics\base\direct-memory.h>
#line 105 "C:\\Users\\nagen\\simics-projects\\my-intel-simics-project-1\\logs\\test\\win64\\modules\\dmlc\\test\\scratch\\1.2\\trivial\\locals_1\\T_locals_1.h"
#undef DMLDIR_DIRECT_MEMORY_H

#define DMLDIR_MAP_TARGET_H "C:\\Users\\nagen\\simics-projects\\my-intel-simics-project-1\\win64\\bin\\dml\\api\\6\\1.2\\simics\\base\\map-target.h"
#line 16 "C:\\Users\\nagen\\simics-projects\\my-intel-simics-project-1\\win64\\bin\\dml\\api\\6\\1.2\\simics\\base\\map-target.dml"

#include <simics\base\map-target.h>
#line 112 "C:\\Users\\nagen\\simics-projects\\my-intel-simics-project-1\\logs\\test\\win64\\modules\\dmlc\\test\\scratch\\1.2\\trivial\\locals_1\\T_locals_1.h"
#undef DMLDIR_MAP_TARGET_H

#define DMLDIR_NOTIFIER_H "C:\\Users\\nagen\\simics-projects\\my-intel-simics-project-1\\win64\\bin\\dml\\api\\6\\1.2\\simics\\base\\notifier.h"
#line 16 "C:\\Users\\nagen\\simics-projects\\my-intel-simics-project-1\\win64\\bin\\dml\\api\\6\\1.2\\simics\\base\\notifier.dml"

#include <simics\base\notifier.h>
#line 119 "C:\\Users\\nagen\\simics-projects\\my-intel-simics-project-1\\logs\\test\\win64\\modules\\dmlc\\test\\scratch\\1.2\\trivial\\locals_1\\T_locals_1.h"
#undef DMLDIR_NOTIFIER_H

#define DMLDIR_OBJECT_LOCKS_H "C:\\Users\\nagen\\simics-projects\\my-intel-simics-project-1\\win64\\bin\\dml\\api\\6\\1.2\\simics\\base\\object-locks.h"
#line 16 "C:\\Users\\nagen\\simics-projects\\my-intel-simics-project-1\\win64\\bin\\dml\\api\\6\\1.2\\simics\\base\\object-locks.dml"

#include <simics\base\object-locks.h>
#line 126 "C:\\Users\\nagen\\simics-projects\\my-intel-simics-project-1\\logs\\test\\win64\\modules\\dmlc\\test\\scratch\\1.2\\trivial\\locals_1\\T_locals_1.h"
#undef DMLDIR_OBJECT_LOCKS_H

#define DMLDIR_SIM_EXCEPTION_H "C:\\Users\\nagen\\simics-projects\\my-intel-simics-project-1\\win64\\bin\\dml\\api\\6\\1.2\\simics\\base\\sim-exception.h"
#line 16 "C:\\Users\\nagen\\simics-projects\\my-intel-simics-project-1\\win64\\bin\\dml\\api\\6\\1.2\\simics\\base\\sim-exception.dml"

#include <simics\base\sim-exception.h>
#line 133 "C:\\Users\\nagen\\simics-projects\\my-intel-simics-project-1\\logs\\test\\win64\\modules\\dmlc\\test\\scratch\\1.2\\trivial\\locals_1\\T_locals_1.h"
#undef DMLDIR_SIM_EXCEPTION_H

#define DMLDIR_DBUFFER_H "C:\\Users\\nagen\\simics-projects\\my-intel-simics-project-1\\win64\\bin\\dml\\api\\6\\1.2\\simics\\util\\dbuffer.h"
#line 16 "C:\\Users\\nagen\\simics-projects\\my-intel-simics-project-1\\win64\\bin\\dml\\api\\6\\1.2\\simics\\util\\dbuffer.dml"

#include <simics\util\dbuffer.h>
#line 140 "C:\\Users\\nagen\\simics-projects\\my-intel-simics-project-1\\logs\\test\\win64\\modules\\dmlc\\test\\scratch\\1.2\\trivial\\locals_1\\T_locals_1.h"
#undef DMLDIR_DBUFFER_H

#define DMLDIR_TYPES_H "C:\\Users\\nagen\\simics-projects\\my-intel-simics-project-1\\win64\\bin\\dml\\api\\6\\1.2\\simics\\processor\\types.h"
#line 16 "C:\\Users\\nagen\\simics-projects\\my-intel-simics-project-1\\win64\\bin\\dml\\api\\6\\1.2\\simics\\processor\\types.dml"

#include <simics\processor\types.h>
#line 147 "C:\\Users\\nagen\\simics-projects\\my-intel-simics-project-1\\logs\\test\\win64\\modules\\dmlc\\test\\scratch\\1.2\\trivial\\locals_1\\T_locals_1.h"
#undef DMLDIR_TYPES_H

#define DMLDIR_BREAKPOINTS_H "C:\\Users\\nagen\\simics-projects\\my-intel-simics-project-1\\win64\\bin\\dml\\api\\6\\1.2\\simics\\base\\breakpoints.h"
#line 16 "C:\\Users\\nagen\\simics-projects\\my-intel-simics-project-1\\win64\\bin\\dml\\api\\6\\1.2\\simics\\base\\breakpoints.dml"

#include <simics\base\breakpoints.h>
#line 154 "C:\\Users\\nagen\\simics-projects\\my-intel-simics-project-1\\logs\\test\\win64\\modules\\dmlc\\test\\scratch\\1.2\\trivial\\locals_1\\T_locals_1.h"
#undef DMLDIR_BREAKPOINTS_H

#define DMLDIR_CBDATA_H "C:\\Users\\nagen\\simics-projects\\my-intel-simics-project-1\\win64\\bin\\dml\\api\\6\\1.2\\simics\\base\\cbdata.h"
#line 16 "C:\\Users\\nagen\\simics-projects\\my-intel-simics-project-1\\win64\\bin\\dml\\api\\6\\1.2\\simics\\base\\cbdata.dml"

#include <simics\base\cbdata.h>
#line 161 "C:\\Users\\nagen\\simics-projects\\my-intel-simics-project-1\\logs\\test\\win64\\modules\\dmlc\\test\\scratch\\1.2\\trivial\\locals_1\\T_locals_1.h"
#undef DMLDIR_CBDATA_H

#define DMLDIR_ARITH_H "C:\\Users\\nagen\\simics-projects\\my-intel-simics-project-1\\win64\\bin\\dml\\api\\6\\1.2\\simics\\util\\arith.h"
#line 16 "C:\\Users\\nagen\\simics-projects\\my-intel-simics-project-1\\win64\\bin\\dml\\api\\6\\1.2\\simics\\util\\arith.dml"

#include <simics\util\arith.h>
#line 168 "C:\\Users\\nagen\\simics-projects\\my-intel-simics-project-1\\logs\\test\\win64\\modules\\dmlc\\test\\scratch\\1.2\\trivial\\locals_1\\T_locals_1.h"
#undef DMLDIR_ARITH_H

#define DMLDIR_INT128_H "C:\\Users\\nagen\\simics-projects\\my-intel-simics-project-1\\win64\\bin\\dml\\api\\6\\1.2\\simics\\util\\int128.h"
#line 16 "C:\\Users\\nagen\\simics-projects\\my-intel-simics-project-1\\win64\\bin\\dml\\api\\6\\1.2\\simics\\util\\int128.dml"

#include <simics\util\int128.h>
#line 175 "C:\\Users\\nagen\\simics-projects\\my-intel-simics-project-1\\logs\\test\\win64\\modules\\dmlc\\test\\scratch\\1.2\\trivial\\locals_1\\T_locals_1.h"
#undef DMLDIR_INT128_H

#define DMLDIR_BREAKPOINTS_H "C:\\Users\\nagen\\simics-projects\\my-intel-simics-project-1\\win64\\bin\\dml\\api\\6\\1.2\\simics\\model-iface\\breakpoints.h"
#line 16 "C:\\Users\\nagen\\simics-projects\\my-intel-simics-project-1\\win64\\bin\\dml\\api\\6\\1.2\\simics\\model-iface\\breakpoints.dml"

#include <simics\model-iface\breakpoints.h>
#line 182 "C:\\Users\\nagen\\simics-projects\\my-intel-simics-project-1\\logs\\test\\win64\\modules\\dmlc\\test\\scratch\\1.2\\trivial\\locals_1\\T_locals_1.h"
#undef DMLDIR_BREAKPOINTS_H

#define DMLDIR_GENERIC_SPR_H "C:\\Users\\nagen\\simics-projects\\my-intel-simics-project-1\\win64\\bin\\dml\\api\\6\\1.2\\simics\\processor\\generic-spr.h"
#line 16 "C:\\Users\\nagen\\simics-projects\\my-intel-simics-project-1\\win64\\bin\\dml\\api\\6\\1.2\\simics\\processor\\generic-spr.dml"

#include <simics\processor\generic-spr.h>
#line 189 "C:\\Users\\nagen\\simics-projects\\my-intel-simics-project-1\\logs\\test\\win64\\modules\\dmlc\\test\\scratch\\1.2\\trivial\\locals_1\\T_locals_1.h"
#undef DMLDIR_GENERIC_SPR_H

#define DMLDIR_6_H "C:\\Users\\nagen\\simics-projects\\my-intel-simics-project-1\\win64\\bin\\dml\\api\\6\\1.2\\simics\\obsolete\\6.h"
#line 16 "C:\\Users\\nagen\\simics-projects\\my-intel-simics-project-1\\win64\\bin\\dml\\api\\6\\1.2\\simics\\obsolete\\6.dml"

#include <simics\obsolete\6.h>
#line 196 "C:\\Users\\nagen\\simics-projects\\my-intel-simics-project-1\\logs\\test\\win64\\modules\\dmlc\\test\\scratch\\1.2\\trivial\\locals_1\\T_locals_1.h"
#undef DMLDIR_6_H

#define DMLDIR_DEVICE_API_H "C:\\Users\\nagen\\simics-projects\\my-intel-simics-project-1\\win64\\bin\\dml\\api\\6\\1.2\\simics\\device-api.h"
#line 16 "C:\\Users\\nagen\\simics-projects\\my-intel-simics-project-1\\win64\\bin\\dml\\api\\6\\1.2\\simics\\device-api.dml"

#include <simics\device-api.h>
#line 203 "C:\\Users\\nagen\\simics-projects\\my-intel-simics-project-1\\logs\\test\\win64\\modules\\dmlc\\test\\scratch\\1.2\\trivial\\locals_1\\T_locals_1.h"
#undef DMLDIR_DEVICE_API_H

#define DMLDIR_BITCOUNT_H "C:\\Users\\nagen\\simics-projects\\my-intel-simics-project-1\\win64\\bin\\dml\\api\\6\\1.2\\simics\\util\\bitcount.h"
#line 16 "C:\\Users\\nagen\\simics-projects\\my-intel-simics-project-1\\win64\\bin\\dml\\api\\6\\1.2\\simics\\util\\bitcount.dml"

#include <simics\util\bitcount.h>
#line 210 "C:\\Users\\nagen\\simics-projects\\my-intel-simics-project-1\\logs\\test\\win64\\modules\\dmlc\\test\\scratch\\1.2\\trivial\\locals_1\\T_locals_1.h"
#undef DMLDIR_BITCOUNT_H

#define DMLDIR_IO_MEMORY_H "C:\\Users\\nagen\\simics-projects\\my-intel-simics-project-1\\win64\\bin\\dml\\api\\6\\1.2\\simics\\devs\\io-memory.h"
#line 16 "C:\\Users\\nagen\\simics-projects\\my-intel-simics-project-1\\win64\\bin\\dml\\api\\6\\1.2\\simics\\devs\\io-memory.dml"

#include <simics\devs\io-memory.h>
#line 217 "C:\\Users\\nagen\\simics-projects\\my-intel-simics-project-1\\logs\\test\\win64\\modules\\dmlc\\test\\scratch\\1.2\\trivial\\locals_1\\T_locals_1.h"
#undef DMLDIR_IO_MEMORY_H

#define DMLDIR_MEMORY_H "C:\\Users\\nagen\\simics-projects\\my-intel-simics-project-1\\win64\\bin\\dml\\api\\6\\1.2\\simics\\base\\memory.h"
#line 16 "C:\\Users\\nagen\\simics-projects\\my-intel-simics-project-1\\win64\\bin\\dml\\api\\6\\1.2\\simics\\base\\memory.dml"

#include <simics\base\memory.h>
#line 224 "C:\\Users\\nagen\\simics-projects\\my-intel-simics-project-1\\logs\\test\\win64\\modules\\dmlc\\test\\scratch\\1.2\\trivial\\locals_1\\T_locals_1.h"
#undef DMLDIR_MEMORY_H

#define DMLDIR_MEMORY_TRANSACTION_H "C:\\Users\\nagen\\simics-projects\\my-intel-simics-project-1\\win64\\bin\\dml\\api\\6\\1.2\\simics\\base\\memory-transaction.h"
#line 16 "C:\\Users\\nagen\\simics-projects\\my-intel-simics-project-1\\win64\\bin\\dml\\api\\6\\1.2\\simics\\base\\memory-transaction.dml"

#include <simics\base\memory-transaction.h>
#line 231 "C:\\Users\\nagen\\simics-projects\\my-intel-simics-project-1\\logs\\test\\win64\\modules\\dmlc\\test\\scratch\\1.2\\trivial\\locals_1\\T_locals_1.h"
#undef DMLDIR_MEMORY_TRANSACTION_H

#define DMLDIR_INSTRUMENTATION_PROVIDER_H "C:\\Users\\nagen\\simics-projects\\my-intel-simics-project-1\\win64\\bin\\dml\\api\\6\\1.2\\simics\\model-iface\\instrumentation-provider.h"
#line 16 "C:\\Users\\nagen\\simics-projects\\my-intel-simics-project-1\\win64\\bin\\dml\\api\\6\\1.2\\simics\\model-iface\\instrumentation-provider.dml"

#include <simics\model-iface\instrumentation-provider.h>
#line 238 "C:\\Users\\nagen\\simics-projects\\my-intel-simics-project-1\\logs\\test\\win64\\modules\\dmlc\\test\\scratch\\1.2\\trivial\\locals_1\\T_locals_1.h"
#undef DMLDIR_INSTRUMENTATION_PROVIDER_H

#define DMLDIR_BANK_INSTRUMENTATION_H "C:\\Users\\nagen\\simics-projects\\my-intel-simics-project-1\\win64\\bin\\dml\\api\\6\\1.2\\simics\\model-iface\\bank-instrumentation.h"
#line 16 "C:\\Users\\nagen\\simics-projects\\my-intel-simics-project-1\\win64\\bin\\dml\\api\\6\\1.2\\simics\\model-iface\\bank-instrumentation.dml"

#include <simics\model-iface\bank-instrumentation.h>
#line 245 "C:\\Users\\nagen\\simics-projects\\my-intel-simics-project-1\\logs\\test\\win64\\modules\\dmlc\\test\\scratch\\1.2\\trivial\\locals_1\\T_locals_1.h"
#undef DMLDIR_BANK_INSTRUMENTATION_H

#define DMLDIR_INT_REGISTER_H "C:\\Users\\nagen\\simics-projects\\my-intel-simics-project-1\\win64\\bin\\dml\\api\\6\\1.2\\simics\\model-iface\\int-register.h"
#line 16 "C:\\Users\\nagen\\simics-projects\\my-intel-simics-project-1\\win64\\bin\\dml\\api\\6\\1.2\\simics\\model-iface\\int-register.dml"

#include <simics\model-iface\int-register.h>
#line 252 "C:\\Users\\nagen\\simics-projects\\my-intel-simics-project-1\\logs\\test\\win64\\modules\\dmlc\\test\\scratch\\1.2\\trivial\\locals_1\\T_locals_1.h"
#undef DMLDIR_INT_REGISTER_H

#define DMLDIR_PYWRAP_H "C:\\Users\\nagen\\simics-projects\\my-intel-simics-project-1\\win64\\bin\\dml\\api\\6\\1.2\\simics\\pywrap.h"
#line 16 "C:\\Users\\nagen\\simics-projects\\my-intel-simics-project-1\\win64\\bin\\dml\\api\\6\\1.2\\simics\\pywrap.dml"

#include <simics\pywrap.h>
#line 259 "C:\\Users\\nagen\\simics-projects\\my-intel-simics-project-1\\logs\\test\\win64\\modules\\dmlc\\test\\scratch\\1.2\\trivial\\locals_1\\T_locals_1.h"
#undef DMLDIR_PYWRAP_H

#define DMLDIR_REGISTER_VIEW_H "C:\\Users\\nagen\\simics-projects\\my-intel-simics-project-1\\win64\\bin\\dml\\api\\6\\1.2\\simics\\model-iface\\register-view.h"
#line 16 "C:\\Users\\nagen\\simics-projects\\my-intel-simics-project-1\\win64\\bin\\dml\\api\\6\\1.2\\simics\\model-iface\\register-view.dml"

#include <simics\model-iface\register-view.h>
#line 266 "C:\\Users\\nagen\\simics-projects\\my-intel-simics-project-1\\logs\\test\\win64\\modules\\dmlc\\test\\scratch\\1.2\\trivial\\locals_1\\T_locals_1.h"
#undef DMLDIR_REGISTER_VIEW_H

#define DMLDIR_HASHTAB_H "C:\\Users\\nagen\\simics-projects\\my-intel-simics-project-1\\win64\\bin\\dml\\api\\6\\1.2\\simics\\util\\hashtab.h"
#line 16 "C:\\Users\\nagen\\simics-projects\\my-intel-simics-project-1\\win64\\bin\\dml\\api\\6\\1.2\\simics\\util\\hashtab.dml"

#include <simics\util\hashtab.h>
#line 273 "C:\\Users\\nagen\\simics-projects\\my-intel-simics-project-1\\logs\\test\\win64\\modules\\dmlc\\test\\scratch\\1.2\\trivial\\locals_1\\T_locals_1.h"
#undef DMLDIR_HASHTAB_H

#define DMLDIR_SOBJECT_H "C:\\Users\\nagen\\simics-projects\\my-intel-simics-project-1\\win64\\bin\\dml\\api\\6\\1.2\\simics\\base\\sobject.h"
#line 16 "C:\\Users\\nagen\\simics-projects\\my-intel-simics-project-1\\win64\\bin\\dml\\api\\6\\1.2\\simics\\base\\sobject.dml"

#include <simics\base\sobject.h>
#line 280 "C:\\Users\\nagen\\simics-projects\\my-intel-simics-project-1\\logs\\test\\win64\\modules\\dmlc\\test\\scratch\\1.2\\trivial\\locals_1\\T_locals_1.h"
#undef DMLDIR_SOBJECT_H

#define DMLDIR_VECT_H "C:\\Users\\nagen\\simics-projects\\my-intel-simics-project-1\\win64\\bin\\dml\\api\\6\\1.2\\simics\\util\\vect.h"
#line 16 "C:\\Users\\nagen\\simics-projects\\my-intel-simics-project-1\\win64\\bin\\dml\\api\\6\\1.2\\simics\\util\\vect.dml"

#include <simics\util\vect.h>
#line 287 "C:\\Users\\nagen\\simics-projects\\my-intel-simics-project-1\\logs\\test\\win64\\modules\\dmlc\\test\\scratch\\1.2\\trivial\\locals_1\\T_locals_1.h"
#undef DMLDIR_VECT_H

#define DMLDIR_CONF_OBJECT_H "C:\\Users\\nagen\\simics-projects\\my-intel-simics-project-1\\win64\\bin\\dml\\api\\6\\1.2\\simics\\base\\conf-object.h"
#line 16 "C:\\Users\\nagen\\simics-projects\\my-intel-simics-project-1\\win64\\bin\\dml\\api\\6\\1.2\\simics\\base\\conf-object.dml"

#include <simics\base\conf-object.h>
#line 294 "C:\\Users\\nagen\\simics-projects\\my-intel-simics-project-1\\logs\\test\\win64\\modules\\dmlc\\test\\scratch\\1.2\\trivial\\locals_1\\T_locals_1.h"
#undef DMLDIR_CONF_OBJECT_H

#define DMLDIR_TIME_H "C:\\Users\\nagen\\simics-projects\\my-intel-simics-project-1\\win64\\bin\\dml\\api\\6\\1.2\\simics\\base\\time.h"
#line 16 "C:\\Users\\nagen\\simics-projects\\my-intel-simics-project-1\\win64\\bin\\dml\\api\\6\\1.2\\simics\\base\\time.dml"

#include <simics\base\time.h>
#line 301 "C:\\Users\\nagen\\simics-projects\\my-intel-simics-project-1\\logs\\test\\win64\\modules\\dmlc\\test\\scratch\\1.2\\trivial\\locals_1\\T_locals_1.h"
#undef DMLDIR_TIME_H

#define DMLDIR_EVENT_H "C:\\Users\\nagen\\simics-projects\\my-intel-simics-project-1\\win64\\bin\\dml\\api\\6\\1.2\\simics\\base\\event.h"
#line 16 "C:\\Users\\nagen\\simics-projects\\my-intel-simics-project-1\\win64\\bin\\dml\\api\\6\\1.2\\simics\\base\\event.dml"

#include <simics\base\event.h>
#line 308 "C:\\Users\\nagen\\simics-projects\\my-intel-simics-project-1\\logs\\test\\win64\\modules\\dmlc\\test\\scratch\\1.2\\trivial\\locals_1\\T_locals_1.h"
#undef DMLDIR_EVENT_H

#define DMLDIR_TIME_H "C:\\Users\\nagen\\simics-projects\\my-intel-simics-project-1\\win64\\bin\\dml\\api\\6\\1.2\\simics\\processor\\time.h"
#line 16 "C:\\Users\\nagen\\simics-projects\\my-intel-simics-project-1\\win64\\bin\\dml\\api\\6\\1.2\\simics\\processor\\time.dml"

#include <simics\processor\time.h>
#line 315 "C:\\Users\\nagen\\simics-projects\\my-intel-simics-project-1\\logs\\test\\win64\\modules\\dmlc\\test\\scratch\\1.2\\trivial\\locals_1\\T_locals_1.h"
#undef DMLDIR_TIME_H

#define DMLDIR_EVENT_H "C:\\Users\\nagen\\simics-projects\\my-intel-simics-project-1\\win64\\bin\\dml\\api\\6\\1.2\\simics\\processor\\event.h"
#line 16 "C:\\Users\\nagen\\simics-projects\\my-intel-simics-project-1\\win64\\bin\\dml\\api\\6\\1.2\\simics\\processor\\event.dml"

#include <simics\processor\event.h>
#line 322 "C:\\Users\\nagen\\simics-projects\\my-intel-simics-project-1\\logs\\test\\win64\\modules\\dmlc\\test\\scratch\\1.2\\trivial\\locals_1\\T_locals_1.h"
#undef DMLDIR_EVENT_H

#define DMLDIR_TYPES_H "C:\\Users\\nagen\\simics-projects\\my-intel-simics-project-1\\win64\\bin\\dml\\api\\6\\1.2\\simics\\base\\types.h"
#line 16 "C:\\Users\\nagen\\simics-projects\\my-intel-simics-project-1\\win64\\bin\\dml\\api\\6\\1.2\\simics\\base\\types.dml"

#include <simics\base\types.h>
#line 329 "C:\\Users\\nagen\\simics-projects\\my-intel-simics-project-1\\logs\\test\\win64\\modules\\dmlc\\test\\scratch\\1.2\\trivial\\locals_1\\T_locals_1.h"
#undef DMLDIR_TYPES_H

#define DMLDIR_VERSION_H "C:\\Users\\nagen\\simics-projects\\my-intel-simics-project-1\\win64\\bin\\dml\\api\\6\\1.2\\simics\\base\\version.h"
#line 16 "C:\\Users\\nagen\\simics-projects\\my-intel-simics-project-1\\win64\\bin\\dml\\api\\6\\1.2\\simics\\base\\version.dml"

#include <simics\base\version.h>
#line 336 "C:\\Users\\nagen\\simics-projects\\my-intel-simics-project-1\\logs\\test\\win64\\modules\\dmlc\\test\\scratch\\1.2\\trivial\\locals_1\\T_locals_1.h"
#undef DMLDIR_VERSION_H

#define DMLDIR_BUILD_ID_7_H "C:\\Users\\nagen\\simics-projects\\my-intel-simics-project-1\\win64\\bin\\dml\\api\\6\\1.2\\simics\\build-id-7.h"
#line 16 "C:\\Users\\nagen\\simics-projects\\my-intel-simics-project-1\\win64\\bin\\dml\\api\\6\\1.2\\simics\\build-id-7.dml"

#include <simics\build-id-7.h>
#line 343 "C:\\Users\\nagen\\simics-projects\\my-intel-simics-project-1\\logs\\test\\win64\\modules\\dmlc\\test\\scratch\\1.2\\trivial\\locals_1\\T_locals_1.h"
#undef DMLDIR_BUILD_ID_7_H

#define DMLDIR_BUILD_ID_H "C:\\Users\\nagen\\simics-projects\\my-intel-simics-project-1\\win64\\bin\\dml\\api\\6\\1.2\\simics\\build-id.h"
#line 16 "C:\\Users\\nagen\\simics-projects\\my-intel-simics-project-1\\win64\\bin\\dml\\api\\6\\1.2\\simics\\build-id.dml"

#include <simics\build-id.h>
#line 350 "C:\\Users\\nagen\\simics-projects\\my-intel-simics-project-1\\logs\\test\\win64\\modules\\dmlc\\test\\scratch\\1.2\\trivial\\locals_1\\T_locals_1.h"
#undef DMLDIR_BUILD_ID_H

#define DMLDIR_HOST_INFO_H "C:\\Users\\nagen\\simics-projects\\my-intel-simics-project-1\\win64\\bin\\dml\\api\\6\\1.2\\simics\\host-info.h"
#line 16 "C:\\Users\\nagen\\simics-projects\\my-intel-simics-project-1\\win64\\bin\\dml\\api\\6\\1.2\\simics\\host-info.dml"

#include <simics\host-info.h>
#line 357 "C:\\Users\\nagen\\simics-projects\\my-intel-simics-project-1\\logs\\test\\win64\\modules\\dmlc\\test\\scratch\\1.2\\trivial\\locals_1\\T_locals_1.h"
#undef DMLDIR_HOST_INFO_H

#define DMLDIR_BASE_TYPES_H "C:\\Users\\nagen\\simics-projects\\my-intel-simics-project-1\\win64\\bin\\dml\\api\\6\\1.2\\simics\\base-types.h"
#line 16 "C:\\Users\\nagen\\simics-projects\\my-intel-simics-project-1\\win64\\bin\\dml\\api\\6\\1.2\\simics\\base-types.dml"

#include <simics\base-types.h>
#line 364 "C:\\Users\\nagen\\simics-projects\\my-intel-simics-project-1\\logs\\test\\win64\\modules\\dmlc\\test\\scratch\\1.2\\trivial\\locals_1\\T_locals_1.h"
#undef DMLDIR_BASE_TYPES_H

#define DMLDIR_STRBUF_H "C:\\Users\\nagen\\simics-projects\\my-intel-simics-project-1\\win64\\bin\\dml\\api\\6\\1.2\\simics\\util\\strbuf.h"
#line 16 "C:\\Users\\nagen\\simics-projects\\my-intel-simics-project-1\\win64\\bin\\dml\\api\\6\\1.2\\simics\\util\\strbuf.dml"

#include <simics\util\strbuf.h>
#line 371 "C:\\Users\\nagen\\simics-projects\\my-intel-simics-project-1\\logs\\test\\win64\\modules\\dmlc\\test\\scratch\\1.2\\trivial\\locals_1\\T_locals_1.h"
#undef DMLDIR_STRBUF_H

#define DMLDIR_HELP_MACROS_H "C:\\Users\\nagen\\simics-projects\\my-intel-simics-project-1\\win64\\bin\\dml\\api\\6\\1.2\\simics\\util\\help-macros.h"
#line 16 "C:\\Users\\nagen\\simics-projects\\my-intel-simics-project-1\\win64\\bin\\dml\\api\\6\\1.2\\simics\\util\\help-macros.dml"

#include <simics\util\help-macros.h>
#line 378 "C:\\Users\\nagen\\simics-projects\\my-intel-simics-project-1\\logs\\test\\win64\\modules\\dmlc\\test\\scratch\\1.2\\trivial\\locals_1\\T_locals_1.h"
#undef DMLDIR_HELP_MACROS_H

#define DMLDIR_MODULE_HOST_CONFIG_H "C:\\Users\\nagen\\simics-projects\\my-intel-simics-project-1\\win64\\bin\\dml\\api\\6\\1.2\\simics\\module-host-config.h"
#line 16 "C:\\Users\\nagen\\simics-projects\\my-intel-simics-project-1\\win64\\bin\\dml\\api\\6\\1.2\\simics\\module-host-config.dml"

#include <simics\module-host-config.h>
#line 385 "C:\\Users\\nagen\\simics-projects\\my-intel-simics-project-1\\logs\\test\\win64\\modules\\dmlc\\test\\scratch\\1.2\\trivial\\locals_1\\T_locals_1.h"
#undef DMLDIR_MODULE_HOST_CONFIG_H

#define DMLDIR_ALLOC_H "C:\\Users\\nagen\\simics-projects\\my-intel-simics-project-1\\win64\\bin\\dml\\api\\6\\1.2\\simics\\util\\alloc.h"
#line 16 "C:\\Users\\nagen\\simics-projects\\my-intel-simics-project-1\\win64\\bin\\dml\\api\\6\\1.2\\simics\\util\\alloc.dml"

#include <simics\util\alloc.h>
#line 392 "C:\\Users\\nagen\\simics-projects\\my-intel-simics-project-1\\logs\\test\\win64\\modules\\dmlc\\test\\scratch\\1.2\\trivial\\locals_1\\T_locals_1.h"
#undef DMLDIR_ALLOC_H

#define DMLDIR_ATTR_VALUE_H "C:\\Users\\nagen\\simics-projects\\my-intel-simics-project-1\\win64\\bin\\dml\\api\\6\\1.2\\simics\\base\\attr-value.h"
#line 16 "C:\\Users\\nagen\\simics-projects\\my-intel-simics-project-1\\win64\\bin\\dml\\api\\6\\1.2\\simics\\base\\attr-value.dml"

#include <simics\base\attr-value.h>
#line 399 "C:\\Users\\nagen\\simics-projects\\my-intel-simics-project-1\\logs\\test\\win64\\modules\\dmlc\\test\\scratch\\1.2\\trivial\\locals_1\\T_locals_1.h"
#undef DMLDIR_ATTR_VALUE_H

#define DMLDIR_PYTHON_H "C:\\Users\\nagen\\simics-projects\\my-intel-simics-project-1\\win64\\bin\\dml\\api\\6\\1.2\\simics\\simulator\\python.h"
#line 16 "C:\\Users\\nagen\\simics-projects\\my-intel-simics-project-1\\win64\\bin\\dml\\api\\6\\1.2\\simics\\simulator\\python.dml"

#include <simics\simulator\python.h>
#line 406 "C:\\Users\\nagen\\simics-projects\\my-intel-simics-project-1\\logs\\test\\win64\\modules\\dmlc\\test\\scratch\\1.2\\trivial\\locals_1\\T_locals_1.h"
#undef DMLDIR_PYTHON_H

#define DMLDIR_DML_BUILTINS_H "C:\\Users\\nagen\\simics-projects\\my-intel-simics-project-1\\win64\\bin\\dml\\1.2\\dml-builtins.h"
#line 14 "C:\\Users\\nagen\\simics-projects\\my-intel-simics-project-1\\win64\\bin\\dml\\1.2\\dml-builtins.dml"

    #include <simics/dmllib.h>
#line 413 "C:\\Users\\nagen\\simics-projects\\my-intel-simics-project-1\\logs\\test\\win64\\modules\\dmlc\\test\\scratch\\1.2\\trivial\\locals_1\\T_locals_1.h"
#undef DMLDIR_DML_BUILTINS_H

#define DMLDIR_DML_BUILTINS_H "C:\\Users\\nagen\\simics-projects\\my-intel-simics-project-1\\win64\\bin\\dml\\1.2\\dml-builtins.h"
#line 153 "C:\\Users\\nagen\\simics-projects\\my-intel-simics-project-1\\win64\\bin\\dml\\1.2\\dml-builtins.dml"

  #define _dml_strcpy strcpy
  #define _dml_strlen strlen
#line 421 "C:\\Users\\nagen\\simics-projects\\my-intel-simics-project-1\\logs\\test\\win64\\modules\\dmlc\\test\\scratch\\1.2\\trivial\\locals_1\\T_locals_1.h"
#undef DMLDIR_DML_BUILTINS_H


#include <simics/util/help-macros.h>
#include <stdint.h>
#include "T_locals_1-struct.h"

typedef _traitref_t object;
typedef conf_object_t processor_t;



struct _object {
};



struct test {
    conf_object_t obj;
    _dml_immediate_after_state_t *_immediate_after_state;
    _dml_detached_hook_queue_t *_detached_hook_queue_stack;
    bool _has_state_callbacks;
    bool _issuing_state_callbacks;
    dml_qname_cache_t _qname_cache;
    ht_int_table_t _subsequent_log_ht;
};
// allows generated code to store device struct offsets in uint32,
// which saves space
STATIC_ASSERT(sizeof(struct test) <= UINT32_MAX);
static const uint64 Register_Read UNUSED = 1ULL;
static const uint64 Register_Write UNUSED = 2ULL;

void hard_reset_test(test_t *_obj);
void soft_reset_test(test_t *_obj);

#endif /* not T_LOCALS_1_H */
