/* Generated by dmlc, do not edit! */

#ifndef T_LOCALS_1_STRUCT_H
#define T_LOCALS_1_STRUCT_H

typedef struct test test_t;

conf_class_t *_initialize_T_locals_1(void);


#endif /* not T_LOCALS_1_STRUCT_H */
