/* Generated by dmlc, do not edit! */

#ifndef T_1_2_REGISTER_VIEW_INQUIRY_STRUCT_H
#define T_1_2_REGISTER_VIEW_INQUIRY_STRUCT_H

typedef struct test test_t;

conf_class_t *_initialize_T_1_2_register_view_inquiry(void);


#endif /* not T_1_2_REGISTER_VIEW_INQUIRY_STRUCT_H */
