/*
 * Generated by dmlc, do not edit!
 *
 * Source files:
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\modules\dmlc\test\1.2\layout\T_simple.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\modules\dmlc\test\1.2\testing.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\1.2\dml-builtins.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\simulator\python.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\base\attr-value.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\util\alloc.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\module-host-config.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\util\help-macros.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\util\strbuf.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\base-types.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\host-info.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\build-id.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\build-id-7.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\base\version.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\base\types.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\processor\event.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\processor\time.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\base\event.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\base\time.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\base\conf-object.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\util\vect.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\base\sobject.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\util\hashtab.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\model-iface\register-view.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\pywrap.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\model-iface\int-register.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\model-iface\bank-instrumentation.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\model-iface\instrumentation-provider.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\base\memory-transaction.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\base\memory.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\devs\io-memory.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\1.2\simics-api.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\util\bitcount.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\1.2\simics-processor.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\1.2\simics-memory.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\1.2\simics-hindsight.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\1.2\simics-event.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\1.2\simics-device.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\1.2\simics-configuration.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\1.2\simics-breakpoints.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\1.2\simics-types.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\device-api.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\obsolete\6.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\processor\generic-spr.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\model-iface\breakpoints.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\util\int128.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\util\arith.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\base\cbdata.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\base\breakpoints.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\processor\types.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\util\dbuffer.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\base\sim-exception.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\base\object-locks.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\base\notifier.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\base\map-target.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\base\direct-memory.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\base\transaction.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\base\hap-producer.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\base\global-notifier.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\base\configuration.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\base\log.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\base\clock.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\model-iface\cycle.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\base\local-time.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\base\bigtime.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\base\duration.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\base\callbacks.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\util\frags.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\util\swabber.dml
 */

#ifndef SIMICS_6_API
#define SIMICS_6_API
#endif

#include "T_simple.h"
#include "T_simple-protos.c"

static attr_value_t get_runtest(conf_object_t *_obj, lang_void *_aux)
{
    test_t *_dev UNUSED = (test_t*)_obj;
    attr_value_t _val0;
    attr_value_t v3_value UNUSED ;
    memset((void *)&v3_value, 0, sizeof(attr_value_t ));
    #line 311 "C:\\\\Users\\\\nagen\\\\simics-projects\\\\my-intel-simics-project-1\\\\win64\\\\bin\\\\dml\\\\1.2\\\\dml-builtins.dml"
    {
        #line 386 "C:\\\\Users\\\\nagen\\\\simics-projects\\\\my-intel-simics-project-1\\\\win64\\\\bin\\\\dml\\\\1.2\\\\dml-builtins.dml"
        attr_value_t v6_value UNUSED ;
        #line 386 "C:\\\\Users\\\\nagen\\\\simics-projects\\\\my-intel-simics-project-1\\\\win64\\\\bin\\\\dml\\\\1.2\\\\dml-builtins.dml"
        memset((void *)&v6_value, 0, sizeof(attr_value_t ));
        {
            #line 21 "C:\\\\Users\\\\nagen\\\\simics-projects\\\\my-intel-simics-project-1\\\\modules\\\\dmlc\\\\test\\\\1.2\\\\testing.dml"
            attr_value_t v8_value UNUSED ;
            #line 21 "C:\\\\Users\\\\nagen\\\\simics-projects\\\\my-intel-simics-project-1\\\\modules\\\\dmlc\\\\test\\\\1.2\\\\testing.dml"
            memset((void *)&v8_value, 0, sizeof(attr_value_t ));
            #line 21 "C:\\\\Users\\\\nagen\\\\simics-projects\\\\my-intel-simics-project-1\\\\modules\\\\dmlc\\\\test\\\\1.2\\\\testing.dml"
            {
                bool v9_result UNUSED  = 1;
                {
                    #line 184 "C:\\\\Users\\\\nagen\\\\simics-projects\\\\my-intel-simics-project-1\\\\modules\\\\dmlc\\\\test\\\\1.2\\\\layout\\\\T_simple.dml"
                    bool v10_ok UNUSED  = 0;
                    {
                        v10_ok = 1;
                        bool v11_b UNUSED  = 0;
                        {
                            #line 188 "C:\\\\Users\\\\nagen\\\\simics-projects\\\\my-intel-simics-project-1\\\\modules\\\\dmlc\\\\test\\\\1.2\\\\layout\\\\T_simple.dml"
                            bool v12__ret_ok UNUSED  = 0;
                            #line 188 "C:\\\\Users\\\\nagen\\\\simics-projects\\\\my-intel-simics-project-1\\\\modules\\\\dmlc\\\\test\\\\1.2\\\\layout\\\\T_simple.dml"
                            if (_DML_M_betest(_dev, &v12__ret_ok))
                            #line 188 "C:\\\\Users\\\\nagen\\\\simics-projects\\\\my-intel-simics-project-1\\\\modules\\\\dmlc\\\\test\\\\1.2\\\\layout\\\\T_simple.dml"
                            goto throw1;
                            #line 188 "C:\\\\Users\\\\nagen\\\\simics-projects\\\\my-intel-simics-project-1\\\\modules\\\\dmlc\\\\test\\\\1.2\\\\layout\\\\T_simple.dml"
                            v11_b = v12__ret_ok;
                            #line 119 "C:\\Users\\nagen\\simics-projects\\my-intel-simics-project-1\\logs\\test\\win64\\modules\\dmlc\\test\\scratch\\1.2\\layout\\simple\\T_simple.c"
                        }
                        #line 189 "C:\\\\Users\\\\nagen\\\\simics-projects\\\\my-intel-simics-project-1\\\\modules\\\\dmlc\\\\test\\\\1.2\\\\layout\\\\T_simple.dml"
                        v10_ok = v10_ok && v11_b;
                        {
                            #line 190 "C:\\\\Users\\\\nagen\\\\simics-projects\\\\my-intel-simics-project-1\\\\modules\\\\dmlc\\\\test\\\\1.2\\\\layout\\\\T_simple.dml"
                            bool v13__ret_ok UNUSED  = 0;
                            #line 190 "C:\\\\Users\\\\nagen\\\\simics-projects\\\\my-intel-simics-project-1\\\\modules\\\\dmlc\\\\test\\\\1.2\\\\layout\\\\T_simple.dml"
                            if (_DML_M_letest(_dev, &v13__ret_ok))
                            #line 190 "C:\\\\Users\\\\nagen\\\\simics-projects\\\\my-intel-simics-project-1\\\\modules\\\\dmlc\\\\test\\\\1.2\\\\layout\\\\T_simple.dml"
                            goto throw1;
                            #line 190 "C:\\\\Users\\\\nagen\\\\simics-projects\\\\my-intel-simics-project-1\\\\modules\\\\dmlc\\\\test\\\\1.2\\\\layout\\\\T_simple.dml"
                            v11_b = v13__ret_ok;
                            #line 132 "C:\\Users\\nagen\\simics-projects\\my-intel-simics-project-1\\logs\\test\\win64\\modules\\dmlc\\test\\scratch\\1.2\\layout\\simple\\T_simple.c"
                        }
                        #line 191 "C:\\\\Users\\\\nagen\\\\simics-projects\\\\my-intel-simics-project-1\\\\modules\\\\dmlc\\\\test\\\\1.2\\\\layout\\\\T_simple.dml"
                        v10_ok = v10_ok && v11_b;
                    }
                    #line 184 "C:\\\\Users\\\\nagen\\\\simics-projects\\\\my-intel-simics-project-1\\\\modules\\\\dmlc\\\\test\\\\1.2\\\\layout\\\\T_simple.dml"
                    v9_result = v10_ok;
                    #line 23 "C:\\\\Users\\\\nagen\\\\simics-projects\\\\my-intel-simics-project-1\\\\modules\\\\dmlc\\\\test\\\\1.2\\\\testing.dml"
                }
                v8_value = SIM_make_attr_boolean(v9_result);
            }
            #line 21 "C:\\\\Users\\\\nagen\\\\simics-projects\\\\my-intel-simics-project-1\\\\modules\\\\dmlc\\\\test\\\\1.2\\\\testing.dml"
            v6_value = v8_value;
            #line 387 "C:\\\\Users\\\\nagen\\\\simics-projects\\\\my-intel-simics-project-1\\\\win64\\\\bin\\\\dml\\\\1.2\\\\dml-builtins.dml"
        }
        #line 386 "C:\\\\Users\\\\nagen\\\\simics-projects\\\\my-intel-simics-project-1\\\\win64\\\\bin\\\\dml\\\\1.2\\\\dml-builtins.dml"
        v3_value = v6_value;
        #line 311 "C:\\\\Users\\\\nagen\\\\simics-projects\\\\my-intel-simics-project-1\\\\win64\\\\bin\\\\dml\\\\1.2\\\\dml-builtins.dml"
    }
    if (false) throw1:
    #line 312 "C:\\\\Users\\\\nagen\\\\simics-projects\\\\my-intel-simics-project-1\\\\win64\\\\bin\\\\dml\\\\1.2\\\\dml-builtins.dml"
    {
        SIM_attribute_error("Uncaught DML exception");
        v3_value = SIM_make_attr_invalid();
    }
    #line 157 "C:\\Users\\nagen\\simics-projects\\my-intel-simics-project-1\\logs\\test\\win64\\modules\\dmlc\\test\\scratch\\1.2\\layout\\simple\\T_simple.c"
    _val0 = v3_value;
    return _val0;
}

static conf_object_t *
test_alloc(conf_class_t *cls)
{
    test_t *_dev = MM_ZALLOC(1, test_t);
    _dev->_immediate_after_state = MM_ZALLOC(1, _dml_immediate_after_state_t);
    return &_dev->obj;
}

static lang_void *
test_init(conf_object_t *_obj)
{
    test_t *_dev = (test_t*)_obj;
    _init_port_objs(_dev);
    _init_static_vars(_dev);
    _init_data_objs(_dev);
    ht_init_int_table(&(_dev->_subsequent_log_ht));
    QINIT(_dev->_immediate_after_state->queue);
    if (_DML_M_init(_dev))
    return 0;
    if (_DML_M_hard_reset(_dev))
    return 0;
    SIM_add_notifier(_obj, Sim_Notify_Object_Delete, _obj, test_pre_delete, NULL);
    return _obj;
}

static void test_finalize(conf_object_t *_obj)
{
    test_t *_dev UNUSED = (test_t *)_obj;
}

static void test_objects_finalized(conf_object_t *_obj)
{
    test_t *_dev UNUSED = (test_t *)_obj;
    _dev->_immediate_after_state->warn_upon_deletion = true;
    _DML_execute_immediate_afters_now(_obj, _dev->_immediate_after_state);
}

static void test_pre_delete(conf_object_t *_subscriber, conf_object_t *_obj, lang_void *_data)
{
    test_t *_dev = (test_t *)_obj;
    _DML_pre_delete_cancel_immediate_afters(_obj, _dev->_immediate_after_state);
    if (SIM_object_clock(_obj)) {
        _cancel_simple_delay_events(_obj, SIM_object_clock(_obj), NULL);
        _cancel_simple_delay_events(_obj, SIM_picosecond_clock(_obj), NULL);
    }
    test_deinit(_obj);
}

static void test_deinit(conf_object_t *_obj)
{
    test_t *_dev UNUSED = (test_t *)_obj;
    _DML_execute_immediate_afters_now(_obj, _dev->_immediate_after_state);
    _free_table(&_dev->_subsequent_log_ht);
    QFREE(_dev->_immediate_after_state->queue);
    if (likely(!_dev->_immediate_after_state->posted)) {
        MM_FREE(_dev->_immediate_after_state);
    } else {
        _dev->_immediate_after_state->deleted = true;
    }
}

static void test_dealloc(conf_object_t *dev)
{
    MM_FREE(dev);
}

static const _id_info_t _id_infos[2] UNUSED = {
    {"dev", NULL, 0, 1},
    {"runtest", NULL, 0, 2}
};
static ht_str_table_t _id_info_ht UNUSED = HT_STR_NULL(false);
static void * const _object_vtables[2] UNUSED = {(&_tr__dev__object), (&_tr_runtest__object)};
static void _startup_calls(void)
{
}
static void _init_data_objs(test_t *_dev)
{
    #line 274 "C:\\\\Users\\\\nagen\\\\simics-projects\\\\my-intel-simics-project-1\\\\win64\\\\bin\\\\dml\\\\1.2\\\\dml-builtins.dml"
    _dev->_has_state_callbacks = 0;
    #line 241 "C:\\Users\\nagen\\simics-projects\\my-intel-simics-project-1\\logs\\test\\win64\\modules\\dmlc\\test\\scratch\\1.2\\layout\\simple\\T_simple.c"
    #line 273 "C:\\\\Users\\\\nagen\\\\simics-projects\\\\my-intel-simics-project-1\\\\win64\\\\bin\\\\dml\\\\1.2\\\\dml-builtins.dml"
    _dev->_issuing_state_callbacks = 0;
    #line 244 "C:\\Users\\nagen\\simics-projects\\my-intel-simics-project-1\\logs\\test\\win64\\modules\\dmlc\\test\\scratch\\1.2\\layout\\simple\\T_simple.c"
}

void
hard_reset_test(test_t *_obj)
{
    test_t *_dev UNUSED = (test_t *)_obj;

    if (_DML_M_hard_reset(_dev))
    SIM_LOG_ERROR(&_dev->obj, 0, "Uncaught DML exception");
}

void
soft_reset_test(test_t *_obj)
{
    test_t *_dev UNUSED = (test_t *)_obj;

    if (_DML_M_soft_reset(_dev))
    SIM_LOG_ERROR(&_dev->obj, 0, "Uncaught DML exception");
}

/* init */
static bool _DML_M_init(test_t *_dev)
#line 247 "C:\\\\Users\\\\nagen\\\\simics-projects\\\\my-intel-simics-project-1\\\\win64\\\\bin\\\\dml\\\\1.2\\\\dml-builtins.dml"
{
    #line 251 "C:\\\\Users\\\\nagen\\\\simics-projects\\\\my-intel-simics-project-1\\\\win64\\\\bin\\\\dml\\\\1.2\\\\dml-builtins.dml"
    return 0;
    #line 251 "C:\\\\Users\\\\nagen\\\\simics-projects\\\\my-intel-simics-project-1\\\\win64\\\\bin\\\\dml\\\\1.2\\\\dml-builtins.dml"
}
#line 273 "C:\\Users\\nagen\\simics-projects\\my-intel-simics-project-1\\logs\\test\\win64\\modules\\dmlc\\test\\scratch\\1.2\\layout\\simple\\T_simple.c"

/* letest */
static bool _DML_M_letest(test_t *_dev, bool *ok)
#line 126 "C:\\\\Users\\\\nagen\\\\simics-projects\\\\my-intel-simics-project-1\\\\modules\\\\dmlc\\\\test\\\\1.2\\\\layout\\\\T_simple.dml"
{
    #line 126 "C:\\\\Users\\\\nagen\\\\simics-projects\\\\my-intel-simics-project-1\\\\modules\\\\dmlc\\\\test\\\\1.2\\\\layout\\\\T_simple.dml"
    bool v28_ok UNUSED  = 0;
    #line 126 "C:\\\\Users\\\\nagen\\\\simics-projects\\\\my-intel-simics-project-1\\\\modules\\\\dmlc\\\\test\\\\1.2\\\\layout\\\\T_simple.dml"
    {
        v28_ok = 1;
        #line 129 "C:\\\\Users\\\\nagen\\\\simics-projects\\\\my-intel-simics-project-1\\\\modules\\\\dmlc\\\\test\\\\1.2\\\\layout\\\\T_simple.dml"
        if ((uint64 )sizeof(ledesc ) != 38)
        #line 129 "C:\\\\Users\\\\nagen\\\\simics-projects\\\\my-intel-simics-project-1\\\\modules\\\\dmlc\\\\test\\\\1.2\\\\layout\\\\T_simple.dml"
        {
            SIM_LOG_ERROR(&_dev->obj, 0, "wrong size: %lld", (uint64 )((int )sizeof(ledesc )));
            v28_ok = 0;
        }
        #line 134 "C:\\\\Users\\\\nagen\\\\simics-projects\\\\my-intel-simics-project-1\\\\modules\\\\dmlc\\\\test\\\\1.2\\\\layout\\\\T_simple.dml"
        uint8 v29_buf[0x100] UNUSED ;
        #line 134 "C:\\\\Users\\\\nagen\\\\simics-projects\\\\my-intel-simics-project-1\\\\modules\\\\dmlc\\\\test\\\\1.2\\\\layout\\\\T_simple.dml"
        memset((void *)&v29_buf, 0, sizeof(uint8 [0x100]));
        int v29_i UNUSED  = 0;
        for (v29_i = 0; v29_i < 0x100; (v29_i)++)
        v29_buf[v29_i] = v29_i;
        #line 139 "C:\\\\Users\\\\nagen\\\\simics-projects\\\\my-intel-simics-project-1\\\\modules\\\\dmlc\\\\test\\\\1.2\\\\layout\\\\T_simple.dml"
        ledesc *v29_d UNUSED  = (ledesc *)v29_buf;
        #line 142 "C:\\\\Users\\\\nagen\\\\simics-projects\\\\my-intel-simics-project-1\\\\modules\\\\dmlc\\\\test\\\\1.2\\\\layout\\\\T_simple.dml"
        if (!(((((((dml_load_uint32_le_t(v29_d->a) == 0x3020100 && dml_load_uint16_le_t(v29_d->b) == 0x504) && dml_load_uint16_le_t(v29_d->c) == 0x706) && dml_load_uint24_le_t(v29_d->d) == 0xb0a09) && dml_load_uint40_le_t(v29_d->e40) == 0x100f0e0d0cULL) && dml_load_uint48_le_t(v29_d->e48) == 0x161514131211ULL) && dml_load_uint56_le_t(v29_d->e56) == 0x1d1c1b1a191817ULL) && dml_load_uint64_le_t(v29_d->e64) == 0x2524232221201f1eULL))
        #line 149 "C:\\\\Users\\\\nagen\\\\simics-projects\\\\my-intel-simics-project-1\\\\modules\\\\dmlc\\\\test\\\\1.2\\\\layout\\\\T_simple.dml"
        {
            SIM_LOG_ERROR(&_dev->obj, 0, "wrong values read");
            v28_ok = 0;
        }
        #line 155 "C:\\\\Users\\\\nagen\\\\simics-projects\\\\my-intel-simics-project-1\\\\modules\\\\dmlc\\\\test\\\\1.2\\\\layout\\\\T_simple.dml"
        dml_copy_uint32_le_t(&v29_d->a, dml_store_uint32_le_t(0x11121314ULL));
        dml_copy_uint16_le_t(&v29_d->b, dml_store_uint16_le_t(0x2122ULL));
        dml_copy_uint16_le_t(&v29_d->c, dml_store_uint16_le_t(0x3132ULL));
        dml_copy_uint24_le_t(&v29_d->d, dml_store_uint24_le_t(0x414243ULL));
        dml_copy_uint40_le_t(&v29_d->e40, dml_store_uint40_le_t(0x5152535455ULL));
        dml_copy_uint48_le_t(&v29_d->e48, dml_store_uint48_le_t(0x616263646566ULL));
        dml_copy_uint56_le_t(&v29_d->e56, dml_store_uint56_le_t(0x71727374757677ULL));
        dml_copy_uint64_le_t(&v29_d->e64, dml_store_uint64_le_t(0x8182838485868788ULL));
        if (((((((((((((((((((((((((((((((((((((v29_buf[0] != 20 || v29_buf[1] != 19) || v29_buf[2] != 18) || v29_buf[3] != 17) || v29_buf[4] != 34) || v29_buf[5] != 33) || v29_buf[6] != 50) || v29_buf[7] != 49) || v29_buf[8] != 8) || v29_buf[9] != 67) || v29_buf[10] != 66) || v29_buf[11] != 65) || v29_buf[12] != 85) || v29_buf[13] != 84) || v29_buf[14] != 83) || v29_buf[15] != 82) || v29_buf[16] != 81) || v29_buf[17] != 102) || v29_buf[18] != 101) || v29_buf[19] != 100) || v29_buf[20] != 99) || v29_buf[21] != 98) || v29_buf[22] != 97) || v29_buf[23] != 119) || v29_buf[24] != 118) || v29_buf[25] != 117) || v29_buf[26] != 116) || v29_buf[27] != 115) || v29_buf[28] != 114) || v29_buf[29] != 113) || v29_buf[30] != 136) || v29_buf[31] != 135) || v29_buf[32] != 134) || v29_buf[33] != 133) || v29_buf[34] != 132) || v29_buf[35] != 131) || v29_buf[36] != 130) || v29_buf[37] != 129)
        #line 178 "C:\\\\Users\\\\nagen\\\\simics-projects\\\\my-intel-simics-project-1\\\\modules\\\\dmlc\\\\test\\\\1.2\\\\layout\\\\T_simple.dml"
        {
            SIM_LOG_ERROR(&_dev->obj, 0, "wrong values written");
            v28_ok = 0;
        }
    }
    #line 182 "C:\\\\Users\\\\nagen\\\\simics-projects\\\\my-intel-simics-project-1\\\\modules\\\\dmlc\\\\test\\\\1.2\\\\layout\\\\T_simple.dml"
    *ok = v28_ok;
    #line 182 "C:\\\\Users\\\\nagen\\\\simics-projects\\\\my-intel-simics-project-1\\\\modules\\\\dmlc\\\\test\\\\1.2\\\\layout\\\\T_simple.dml"
    return 0;
    #line 182 "C:\\\\Users\\\\nagen\\\\simics-projects\\\\my-intel-simics-project-1\\\\modules\\\\dmlc\\\\test\\\\1.2\\\\layout\\\\T_simple.dml"
}
#line 329 "C:\\Users\\nagen\\simics-projects\\my-intel-simics-project-1\\logs\\test\\win64\\modules\\dmlc\\test\\scratch\\1.2\\layout\\simple\\T_simple.c"

/* betest */
static bool _DML_M_betest(test_t *_dev, bool *ok)
#line 62 "C:\\\\Users\\\\nagen\\\\simics-projects\\\\my-intel-simics-project-1\\\\modules\\\\dmlc\\\\test\\\\1.2\\\\layout\\\\T_simple.dml"
{
    #line 62 "C:\\\\Users\\\\nagen\\\\simics-projects\\\\my-intel-simics-project-1\\\\modules\\\\dmlc\\\\test\\\\1.2\\\\layout\\\\T_simple.dml"
    bool v33_ok UNUSED  = 0;
    #line 62 "C:\\\\Users\\\\nagen\\\\simics-projects\\\\my-intel-simics-project-1\\\\modules\\\\dmlc\\\\test\\\\1.2\\\\layout\\\\T_simple.dml"
    {
        v33_ok = 1;
        #line 65 "C:\\\\Users\\\\nagen\\\\simics-projects\\\\my-intel-simics-project-1\\\\modules\\\\dmlc\\\\test\\\\1.2\\\\layout\\\\T_simple.dml"
        if ((uint64 )sizeof(bedesc ) != 38)
        #line 65 "C:\\\\Users\\\\nagen\\\\simics-projects\\\\my-intel-simics-project-1\\\\modules\\\\dmlc\\\\test\\\\1.2\\\\layout\\\\T_simple.dml"
        {
            SIM_LOG_ERROR(&_dev->obj, 0, "wrong size: %lld", (uint64 )((int )sizeof(bedesc )));
            v33_ok = 0;
        }
        #line 70 "C:\\\\Users\\\\nagen\\\\simics-projects\\\\my-intel-simics-project-1\\\\modules\\\\dmlc\\\\test\\\\1.2\\\\layout\\\\T_simple.dml"
        uint8 v34_buf[0x100] UNUSED ;
        #line 70 "C:\\\\Users\\\\nagen\\\\simics-projects\\\\my-intel-simics-project-1\\\\modules\\\\dmlc\\\\test\\\\1.2\\\\layout\\\\T_simple.dml"
        memset((void *)&v34_buf, 0, sizeof(uint8 [0x100]));
        int v34_i UNUSED  = 0;
        for (v34_i = 0; v34_i < 0x100; (v34_i)++)
        v34_buf[v34_i] = v34_i;
        #line 75 "C:\\\\Users\\\\nagen\\\\simics-projects\\\\my-intel-simics-project-1\\\\modules\\\\dmlc\\\\test\\\\1.2\\\\layout\\\\T_simple.dml"
        bedesc *v34_d UNUSED  = (bedesc *)v34_buf;
        #line 78 "C:\\\\Users\\\\nagen\\\\simics-projects\\\\my-intel-simics-project-1\\\\modules\\\\dmlc\\\\test\\\\1.2\\\\layout\\\\T_simple.dml"
        if (!(((((((dml_load_uint32_be_t(v34_d->a) == 0x10203 && dml_load_uint16_be_t(v34_d->b) == 0x405) && dml_load_uint16_be_t(v34_d->c) == 0x607) && dml_load_uint24_be_t(v34_d->d) == 0x90a0b) && dml_load_uint40_be_t(v34_d->e40) == 0xc0d0e0f10ULL) && dml_load_uint48_be_t(v34_d->e48) == 0x111213141516ULL) && dml_load_uint56_be_t(v34_d->e56) == 0x1718191a1b1c1dULL) && dml_load_uint64_be_t(v34_d->e64) == 0x1e1f202122232425ULL))
        #line 85 "C:\\\\Users\\\\nagen\\\\simics-projects\\\\my-intel-simics-project-1\\\\modules\\\\dmlc\\\\test\\\\1.2\\\\layout\\\\T_simple.dml"
        {
            SIM_LOG_ERROR(&_dev->obj, 0, "wrong values read");
            v33_ok = 0;
        }
        #line 91 "C:\\\\Users\\\\nagen\\\\simics-projects\\\\my-intel-simics-project-1\\\\modules\\\\dmlc\\\\test\\\\1.2\\\\layout\\\\T_simple.dml"
        dml_copy_uint32_be_t(&v34_d->a, dml_store_uint32_be_t(0x11121314ULL));
        dml_copy_uint16_be_t(&v34_d->b, dml_store_uint16_be_t(0x2122ULL));
        dml_copy_uint16_be_t(&v34_d->c, dml_store_uint16_be_t(0x3132ULL));
        dml_copy_uint24_be_t(&v34_d->d, dml_store_uint24_be_t(0x414243ULL));
        dml_copy_uint40_be_t(&v34_d->e40, dml_store_uint40_be_t(0x5152535455ULL));
        dml_copy_uint48_be_t(&v34_d->e48, dml_store_uint48_be_t(0x616263646566ULL));
        dml_copy_uint56_be_t(&v34_d->e56, dml_store_uint56_be_t(0x71727374757677ULL));
        dml_copy_uint64_be_t(&v34_d->e64, dml_store_uint64_be_t(0x8182838485868788ULL));
        if (((((((((((((((((((((((((((((((((((((v34_buf[0] != 17 || v34_buf[1] != 18) || v34_buf[2] != 19) || v34_buf[3] != 20) || v34_buf[4] != 33) || v34_buf[5] != 34) || v34_buf[6] != 49) || v34_buf[7] != 50) || v34_buf[8] != 8) || v34_buf[9] != 65) || v34_buf[10] != 66) || v34_buf[11] != 67) || v34_buf[12] != 81) || v34_buf[13] != 82) || v34_buf[14] != 83) || v34_buf[15] != 84) || v34_buf[16] != 85) || v34_buf[17] != 97) || v34_buf[18] != 98) || v34_buf[19] != 99) || v34_buf[20] != 100) || v34_buf[21] != 101) || v34_buf[22] != 102) || v34_buf[23] != 113) || v34_buf[24] != 114) || v34_buf[25] != 115) || v34_buf[26] != 116) || v34_buf[27] != 117) || v34_buf[28] != 118) || v34_buf[29] != 119) || v34_buf[30] != 129) || v34_buf[31] != 130) || v34_buf[32] != 131) || v34_buf[33] != 132) || v34_buf[34] != 133) || v34_buf[35] != 134) || v34_buf[36] != 135) || v34_buf[37] != 136)
        #line 114 "C:\\\\Users\\\\nagen\\\\simics-projects\\\\my-intel-simics-project-1\\\\modules\\\\dmlc\\\\test\\\\1.2\\\\layout\\\\T_simple.dml"
        {
            SIM_LOG_ERROR(&_dev->obj, 0, "wrong values written");
            v33_ok = 0;
        }
        #line 120 "C:\\\\Users\\\\nagen\\\\simics-projects\\\\my-intel-simics-project-1\\\\modules\\\\dmlc\\\\test\\\\1.2\\\\layout\\\\T_simple.dml"
        dml_copy_uint32_be_t(&v34_d->a, dml_store_uint32_be_t((uint64 )(dml_load_uint32_be_t(v34_d->a) + 1)));
        dml_copy_uint32_be_t(&v34_d->a, dml_store_uint32_be_t((uint64 )(dml_load_uint32_be_t(v34_d->a) + 1)));
        #line 123 "C:\\\\Users\\\\nagen\\\\simics-projects\\\\my-intel-simics-project-1\\\\modules\\\\dmlc\\\\test\\\\1.2\\\\layout\\\\T_simple.dml"
    }
    #line 123 "C:\\\\Users\\\\nagen\\\\simics-projects\\\\my-intel-simics-project-1\\\\modules\\\\dmlc\\\\test\\\\1.2\\\\layout\\\\T_simple.dml"
    *ok = v33_ok;
    #line 123 "C:\\\\Users\\\\nagen\\\\simics-projects\\\\my-intel-simics-project-1\\\\modules\\\\dmlc\\\\test\\\\1.2\\\\layout\\\\T_simple.dml"
    return 0;
    #line 123 "C:\\\\Users\\\\nagen\\\\simics-projects\\\\my-intel-simics-project-1\\\\modules\\\\dmlc\\\\test\\\\1.2\\\\layout\\\\T_simple.dml"
}
#line 389 "C:\\Users\\nagen\\simics-projects\\my-intel-simics-project-1\\logs\\test\\win64\\modules\\dmlc\\test\\scratch\\1.2\\layout\\simple\\T_simple.c"

/* soft_reset */
static bool _DML_M_soft_reset(test_t *_dev)
#line 1216 "C:\\\\Users\\\\nagen\\\\simics-projects\\\\my-intel-simics-project-1\\\\win64\\\\bin\\\\dml\\\\1.2\\\\dml-builtins.dml"
{
    #line 1218 "C:\\\\Users\\\\nagen\\\\simics-projects\\\\my-intel-simics-project-1\\\\win64\\\\bin\\\\dml\\\\1.2\\\\dml-builtins.dml"
    return 0;
    #line 1218 "C:\\\\Users\\\\nagen\\\\simics-projects\\\\my-intel-simics-project-1\\\\win64\\\\bin\\\\dml\\\\1.2\\\\dml-builtins.dml"
}
#line 399 "C:\\Users\\nagen\\simics-projects\\my-intel-simics-project-1\\logs\\test\\win64\\modules\\dmlc\\test\\scratch\\1.2\\layout\\simple\\T_simple.c"

/* hard_reset */
static bool _DML_M_hard_reset(test_t *_dev)
#line 1211 "C:\\\\Users\\\\nagen\\\\simics-projects\\\\my-intel-simics-project-1\\\\win64\\\\bin\\\\dml\\\\1.2\\\\dml-builtins.dml"
{
    #line 1213 "C:\\\\Users\\\\nagen\\\\simics-projects\\\\my-intel-simics-project-1\\\\win64\\\\bin\\\\dml\\\\1.2\\\\dml-builtins.dml"
    return 0;
    #line 1213 "C:\\\\Users\\\\nagen\\\\simics-projects\\\\my-intel-simics-project-1\\\\win64\\\\bin\\\\dml\\\\1.2\\\\dml-builtins.dml"
}
#line 409 "C:\\Users\\nagen\\simics-projects\\my-intel-simics-project-1\\logs\\test\\win64\\modules\\dmlc\\test\\scratch\\1.2\\layout\\simple\\T_simple.c"

conf_class_t *
_initialize_T_simple(void)
{

    const class_info_t funcs = {
        .alloc = test_alloc,
        .init = test_init,
        .finalize = test_finalize,
        .objects_finalized = test_objects_finalized,
        .dealloc = test_dealloc,
        .description = "test device",
    };

    conf_class_t *class = SIM_create_class("test", &funcs);
    _dev_class = class;
    if (SIM_clear_exception() != SimExc_No_Exception) {
        fprintf(stderr, "Failed to register class test: %s\n", SIM_last_error());
        return NULL;
    }

    _initialize_traits();
    _initialize_identity_ht();
    _initialize_vtable_hts();
    _initialize_typeseq_after_on_hook_hts();
    _register_events(class);
    _DML_register_attribute(class, "runtest", get_runtest, NULL, 0, NULL, Sim_Attr_Pseudo|Sim_Attr_Internal, "b", "Undocumented");

    const char *const log_groups[] = {
        "Register_Read",
        "Register_Write",
        NULL
    };
    SIM_log_register_groups(class, log_groups);

    _startup_calls();
    return class;
}

static void _initialize_vtable_hts(void)
{
}
static void __attribute__((optimize("O0")))
_tinit_object(struct _object *_ret)
{
}
static void __attribute__((optimize("O0"))) _initialize_traits0(void)
{
    _tinit_object(&_tr__dev__object);
    _tinit_object(&_tr_runtest__object);
}
static void __attribute__((optimize("O0"))) _initialize_traits(void)
{
    _initialize_traits0();
}
static const _vtable_list_t *const _each__object UNUSED = NULL;
static void _initialize_typeseq_after_on_hook_hts(void)
{
}
static attr_value_t _simple_event_only_domains_get_value(conf_object_t *_obj, lang_void *data)
{
    return _serialize_simple_event_data(0, NULL, _id_infos, (_simple_event_data_t *)data);
}

static lang_void *_simple_event_only_domains_set_value(conf_object_t *_obj, attr_value_t val)
{
    _simple_event_data_t *out;
    set_error_t error = _deserialize_simple_event_data(NULL, 0, 0, NULL, &_id_info_ht, val, &out);
    if (error != Sim_Set_Ok) {
        out = NULL;
    }
    return out;
}

static void _cancel_simple_delay_events(conf_object_t *_obj, conf_object_t *_clock, const _identity_t *_domain)
{
    int (*_pred)(lang_void *, lang_void *) UNUSED = _domain ? _simple_event_predicate : NULL;
}
static void _cancel_simple_events(conf_object_t *_obj, _identity_t _domain)
{
    test_t *_dev UNUSED = (test_t*)_obj;
    if (!SIM_marked_for_deletion(_obj) && SIM_object_clock(_obj)) {
        _cancel_simple_delay_events(_obj, SIM_object_clock(_obj), &_domain);
        _cancel_simple_delay_events(_obj, SIM_picosecond_clock(_obj), &_domain);
    }
    _DML_cancel_afters_in_detached_hook_queues(_dev->_detached_hook_queue_stack, _domain);
}

static void _initialize_identity_ht(void)
{
    ht_insert_str(&_id_info_ht, "test", &_id_infos[0]);
    for (uint64 i = 0; i < 2; ++i) {
        ht_insert_str(&_id_info_ht, _id_infos[i].logname, &_id_infos[i]);
    }
}
static void _register_events(conf_class_t *class)
{
    return;
}

static void _init_port_objs(test_t *_dev)
{
}
static void _init_static_vars(test_t *_dev)
{
}

// DML serialization functions
static UNUSED bool hard_reset(test_t *_dev)
{
    return _DML_M_hard_reset(_dev);
}
static UNUSED bool soft_reset(test_t *_dev)
{
    return _DML_M_soft_reset(_dev);
}

