/* Generated by dmlc, do not edit! */

#ifndef T_INHERITANCE_FROM_14_STRUCT_H
#define T_INHERITANCE_FROM_14_STRUCT_H

typedef struct test test_t;

conf_class_t *_initialize_T_inheritance_from_14(void);


#endif /* not T_INHERITANCE_FROM_14_STRUCT_H */
