/* Generated by dmlc, do not edit! */

#ifndef T_CHARLIT_STRUCT_H
#define T_CHARLIT_STRUCT_H

typedef struct test test_t;

conf_class_t *_initialize_T_charlit(void);


#endif /* not T_CHARLIT_STRUCT_H */
