/* Generated by dmlc, do not edit! */

#ifndef T_TYPEDEF_1_STRUCT_H
#define T_TYPEDEF_1_STRUCT_H

typedef struct test test_t;

conf_class_t *_initialize_T_typedef_1(void);


#endif /* not T_TYPEDEF_1_STRUCT_H */
