/* Generated by dmlc, do not edit! */

#ifndef T_COMPLEMENT_STRUCT_H
#define T_COMPLEMENT_STRUCT_H

typedef struct test test_t;

conf_class_t *_initialize_T_complement(void);


#endif /* not T_COMPLEMENT_STRUCT_H */
