/* Generated by dmlc, do not edit! */

#ifndef T_PARAMETERS_STRUCT_H
#define T_PARAMETERS_STRUCT_H

typedef struct test test_t;

conf_class_t *_initialize_T_parameters(void);


#endif /* not T_PARAMETERS_STRUCT_H */
