/* Generated by dmlc, do not edit! */

#ifndef T_STACKED_STRUCT_H
#define T_STACKED_STRUCT_H

typedef struct test test_t;

conf_class_t *_initialize_T_stacked(void);


#endif /* not T_STACKED_STRUCT_H */
