/* Generated by dmlc, do not edit! */

#ifndef T_DESTROY_STRUCT_H
#define T_DESTROY_STRUCT_H

typedef struct test test_t;

conf_class_t *_initialize_T_destroy(void);


#endif /* not T_DESTROY_STRUCT_H */
