/* Generated by dmlc, do not edit! */

#ifndef T_INCDEC_LAYOUT_STRUCT_H
#define T_INCDEC_LAYOUT_STRUCT_H

typedef struct foo foo_t;

conf_class_t *_initialize_T_incdec_layout(void);


#endif /* not T_INCDEC_LAYOUT_STRUCT_H */
