/* Generated by dmlc, do not edit! */

#ifndef T_TRAIT_DIAMOND_DEFAULT_STRUCT_H
#define T_TRAIT_DIAMOND_DEFAULT_STRUCT_H

typedef struct test test_t;

conf_class_t *_initialize_T_trait_diamond_default(void);


#endif /* not T_TRAIT_DIAMOND_DEFAULT_STRUCT_H */
