/*
 * Generated by dmlc, do not edit!
 *
 * Source files:
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\modules\dmlc\test\1.2\misc\T_split_output.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\modules\dmlc\test\1.2\testing.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\1.2\dml-builtins.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\simulator\python.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\base\attr-value.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\util\alloc.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\module-host-config.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\util\help-macros.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\util\strbuf.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\base-types.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\host-info.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\build-id.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\build-id-7.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\base\version.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\base\types.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\processor\event.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\processor\time.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\base\event.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\base\time.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\base\conf-object.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\util\vect.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\base\sobject.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\util\hashtab.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\model-iface\register-view.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\pywrap.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\model-iface\int-register.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\model-iface\bank-instrumentation.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\model-iface\instrumentation-provider.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\base\memory-transaction.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\base\memory.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\devs\io-memory.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\1.2\simics-api.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\util\bitcount.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\1.2\simics-processor.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\1.2\simics-memory.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\1.2\simics-hindsight.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\1.2\simics-event.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\1.2\simics-device.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\1.2\simics-configuration.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\1.2\simics-breakpoints.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\1.2\simics-types.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\device-api.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\obsolete\6.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\processor\generic-spr.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\model-iface\breakpoints.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\util\int128.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\util\arith.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\base\cbdata.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\base\breakpoints.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\processor\types.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\util\dbuffer.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\base\sim-exception.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\base\object-locks.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\base\notifier.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\base\map-target.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\base\direct-memory.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\base\transaction.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\base\hap-producer.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\base\global-notifier.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\base\configuration.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\base\log.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\base\clock.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\model-iface\cycle.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\base\local-time.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\base\bigtime.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\base\duration.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\base\callbacks.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\util\frags.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\util\swabber.dml
 */

#ifndef SIMICS_6_API
#define SIMICS_6_API
#endif

#include "T_split.h"
#include "T_split-protos.c"
/* regs.register_view.get_register_value */
bool _DML_M_regs__register_view__get_register_value(test_t *_dev, uint32 reg, uint64 *val)
#line 1085 "C:\\\\Users\\\\nagen\\\\simics-projects\\\\my-intel-simics-project-1\\\\win64\\\\bin\\\\dml\\\\1.2\\\\dml-builtins.dml"
{
    #line 1085 "C:\\\\Users\\\\nagen\\\\simics-projects\\\\my-intel-simics-project-1\\\\win64\\\\bin\\\\dml\\\\1.2\\\\dml-builtins.dml"
    uint64 v161_val UNUSED  = 0;
    #line 1085 "C:\\\\Users\\\\nagen\\\\simics-projects\\\\my-intel-simics-project-1\\\\win64\\\\bin\\\\dml\\\\1.2\\\\dml-builtins.dml"
    {
        attr_value_t v162_args UNUSED ;
        #line 1086 "C:\\\\Users\\\\nagen\\\\simics-projects\\\\my-intel-simics-project-1\\\\win64\\\\bin\\\\dml\\\\1.2\\\\dml-builtins.dml"
        memset((void *)&v162_args, 0, sizeof(attr_value_t ));
        #line 1095 "C:\\\\Users\\\\nagen\\\\simics-projects\\\\my-intel-simics-project-1\\\\win64\\\\bin\\\\dml\\\\1.2\\\\dml-builtins.dml"
        v162_args = SIM_make_attr_list(7, SIM_make_attr_string("test"), SIM_make_attr_string("regs"), SIM_make_attr_string("regs"), SIM_make_attr_uint64(reg), SIM_make_attr_object(&_dev->obj), SIM_make_attr_uint64(0), SIM_make_attr_boolean(1));
        #line 1097 "C:\\\\Users\\\\nagen\\\\simics-projects\\\\my-intel-simics-project-1\\\\win64\\\\bin\\\\dml\\\\1.2\\\\dml-builtins.dml"
        attr_value_t v162_ret UNUSED ;
        #line 1097 "C:\\\\Users\\\\nagen\\\\simics-projects\\\\my-intel-simics-project-1\\\\win64\\\\bin\\\\dml\\\\1.2\\\\dml-builtins.dml"
        memset((void *)&v162_ret, 0, sizeof(attr_value_t ));
        #line 1099 "C:\\\\Users\\\\nagen\\\\simics-projects\\\\my-intel-simics-project-1\\\\win64\\\\bin\\\\dml\\\\1.2\\\\dml-builtins.dml"
        v162_ret = VT_call_python_module_function("register_view", "get_register_value", &v162_args);
        SIM_attr_free(&v162_args);
        #line 1102 "C:\\\\Users\\\\nagen\\\\simics-projects\\\\my-intel-simics-project-1\\\\win64\\\\bin\\\\dml\\\\1.2\\\\dml-builtins.dml"
        v161_val = SIM_attr_integer(v162_ret);
        SIM_attr_free(&v162_ret);
    }
    #line 1104 "C:\\\\Users\\\\nagen\\\\simics-projects\\\\my-intel-simics-project-1\\\\win64\\\\bin\\\\dml\\\\1.2\\\\dml-builtins.dml"
    *val = v161_val;
    #line 1104 "C:\\\\Users\\\\nagen\\\\simics-projects\\\\my-intel-simics-project-1\\\\win64\\\\bin\\\\dml\\\\1.2\\\\dml-builtins.dml"
    return 0;
    #line 1104 "C:\\\\Users\\\\nagen\\\\simics-projects\\\\my-intel-simics-project-1\\\\win64\\\\bin\\\\dml\\\\1.2\\\\dml-builtins.dml"
}
#line 113 "C:\\Users\\nagen\\simics-projects\\my-intel-simics-project-1\\logs\\test\\win64\\modules\\dmlc\\test\\scratch\\split\\T_split-71.c"

