/*
 * Generated by dmlc, do not edit!
 *
 * Source files:
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\modules\dmlc\test\1.2\misc\T_split_output.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\modules\dmlc\test\1.2\testing.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\1.2\dml-builtins.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\simulator\python.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\base\attr-value.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\util\alloc.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\module-host-config.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\util\help-macros.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\util\strbuf.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\base-types.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\host-info.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\build-id.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\build-id-7.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\base\version.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\base\types.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\processor\event.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\processor\time.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\base\event.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\base\time.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\base\conf-object.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\util\vect.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\base\sobject.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\util\hashtab.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\model-iface\register-view.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\pywrap.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\model-iface\int-register.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\model-iface\bank-instrumentation.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\model-iface\instrumentation-provider.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\base\memory-transaction.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\base\memory.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\devs\io-memory.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\1.2\simics-api.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\util\bitcount.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\1.2\simics-processor.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\1.2\simics-memory.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\1.2\simics-hindsight.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\1.2\simics-event.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\1.2\simics-device.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\1.2\simics-configuration.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\1.2\simics-breakpoints.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\1.2\simics-types.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\device-api.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\obsolete\6.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\processor\generic-spr.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\model-iface\breakpoints.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\util\int128.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\util\arith.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\base\cbdata.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\base\breakpoints.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\processor\types.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\util\dbuffer.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\base\sim-exception.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\base\object-locks.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\base\notifier.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\base\map-target.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\base\direct-memory.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\base\transaction.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\base\hap-producer.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\base\global-notifier.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\base\configuration.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\base\log.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\base\clock.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\model-iface\cycle.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\base\local-time.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\base\bigtime.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\base\duration.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\base\callbacks.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\util\frags.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\util\swabber.dml
 */

#ifndef SIMICS_6_API
#define SIMICS_6_API
#endif

#include "T_split.h"
#include "T_split-protos.c"
/* regs.r[$i]._read_access_nopartial */
bool _DML_M_regs__r___read_access_nopartial(test_t *_dev, uint32 _idx0, generic_transaction_t *memop, uint64 *value)
#line 1404 "C:\\\\Users\\\\nagen\\\\simics-projects\\\\my-intel-simics-project-1\\\\win64\\\\bin\\\\dml\\\\1.2\\\\dml-builtins.dml"
{
    #line 1404 "C:\\\\Users\\\\nagen\\\\simics-projects\\\\my-intel-simics-project-1\\\\win64\\\\bin\\\\dml\\\\1.2\\\\dml-builtins.dml"
    uint64 v269_value UNUSED  = 0;
    {
        #line 1405 "C:\\\\Users\\\\nagen\\\\simics-projects\\\\my-intel-simics-project-1\\\\win64\\\\bin\\\\dml\\\\1.2\\\\dml-builtins.dml"
        generic_transaction_t *v271_memop UNUSED  = memop;
        #line 1408 "C:\\\\Users\\\\nagen\\\\simics-projects\\\\my-intel-simics-project-1\\\\win64\\\\bin\\\\dml\\\\1.2\\\\dml-builtins.dml"
        uint64 v271_value UNUSED  = 0;
        #line 1410 "C:\\\\Users\\\\nagen\\\\simics-projects\\\\my-intel-simics-project-1\\\\win64\\\\bin\\\\dml\\\\1.2\\\\dml-builtins.dml"
        if (SIM_get_mem_op_inquiry(v271_memop))
        #line 1410 "C:\\\\Users\\\\nagen\\\\simics-projects\\\\my-intel-simics-project-1\\\\win64\\\\bin\\\\dml\\\\1.2\\\\dml-builtins.dml"
        {
            uint64 v273_full_value UNUSED  = 0;
            {
                #line 1412 "C:\\\\Users\\\\nagen\\\\simics-projects\\\\my-intel-simics-project-1\\\\win64\\\\bin\\\\dml\\\\1.2\\\\dml-builtins.dml"
                uint64 v274__ret_value UNUSED  = 0;
                #line 1412 "C:\\\\Users\\\\nagen\\\\simics-projects\\\\my-intel-simics-project-1\\\\win64\\\\bin\\\\dml\\\\1.2\\\\dml-builtins.dml"
                if (_DML_M_regs__r___get64(_dev, _idx0, &v274__ret_value))
                #line 1412 "C:\\\\Users\\\\nagen\\\\simics-projects\\\\my-intel-simics-project-1\\\\win64\\\\bin\\\\dml\\\\1.2\\\\dml-builtins.dml"
                return 1;
                #line 1412 "C:\\\\Users\\\\nagen\\\\simics-projects\\\\my-intel-simics-project-1\\\\win64\\\\bin\\\\dml\\\\1.2\\\\dml-builtins.dml"
                v273_full_value = v274__ret_value;
                #line 108 "C:\\Users\\nagen\\simics-projects\\my-intel-simics-project-1\\logs\\test\\win64\\modules\\dmlc\\test\\scratch\\split\\T_split-87.c"
            }
            #line 1416 "C:\\\\Users\\\\nagen\\\\simics-projects\\\\my-intel-simics-project-1\\\\win64\\\\bin\\\\dml\\\\1.2\\\\dml-builtins.dml"
            v271_value = v273_full_value;
            #line 1418 "C:\\\\Users\\\\nagen\\\\simics-projects\\\\my-intel-simics-project-1\\\\win64\\\\bin\\\\dml\\\\1.2\\\\dml-builtins.dml"
        }
        #line 1418 "C:\\\\Users\\\\nagen\\\\simics-projects\\\\my-intel-simics-project-1\\\\win64\\\\bin\\\\dml\\\\1.2\\\\dml-builtins.dml"
        else
        #line 1418 "C:\\\\Users\\\\nagen\\\\simics-projects\\\\my-intel-simics-project-1\\\\win64\\\\bin\\\\dml\\\\1.2\\\\dml-builtins.dml"
        {
            #line 1420 "C:\\\\Users\\\\nagen\\\\simics-projects\\\\my-intel-simics-project-1\\\\win64\\\\bin\\\\dml\\\\1.2\\\\dml-builtins.dml"
            {
                #line 1420 "C:\\\\Users\\\\nagen\\\\simics-projects\\\\my-intel-simics-project-1\\\\win64\\\\bin\\\\dml\\\\1.2\\\\dml-builtins.dml"
                generic_transaction_t *v279_memop UNUSED  = v271_memop;
                #line 1425 "C:\\\\Users\\\\nagen\\\\simics-projects\\\\my-intel-simics-project-1\\\\win64\\\\bin\\\\dml\\\\1.2\\\\dml-builtins.dml"
                uint32 v279_value UNUSED  = 0;
                #line 1455 "C:\\\\Users\\\\nagen\\\\simics-projects\\\\my-intel-simics-project-1\\\\win64\\\\bin\\\\dml\\\\1.2\\\\dml-builtins.dml"
                {
                    #line 1171 "C:\\\\Users\\\\nagen\\\\simics-projects\\\\my-intel-simics-project-1\\\\win64\\\\bin\\\\dml\\\\1.2\\\\dml-builtins.dml"
                    uint32 v283_value UNUSED  = 0;
                    {
                        #line 1298 "C:\\\\Users\\\\nagen\\\\simics-projects\\\\my-intel-simics-project-1\\\\win64\\\\bin\\\\dml\\\\1.2\\\\dml-builtins.dml"
                        uint32 v285_value UNUSED  = 0;
                        #line 1300 "C:\\\\Users\\\\nagen\\\\simics-projects\\\\my-intel-simics-project-1\\\\win64\\\\bin\\\\dml\\\\1.2\\\\dml-builtins.dml"
                        v285_value = _dev->regs.r[_idx0];
                        #line 1298 "C:\\\\Users\\\\nagen\\\\simics-projects\\\\my-intel-simics-project-1\\\\win64\\\\bin\\\\dml\\\\1.2\\\\dml-builtins.dml"
                        v283_value = v285_value;
                        #line 1172 "C:\\\\Users\\\\nagen\\\\simics-projects\\\\my-intel-simics-project-1\\\\win64\\\\bin\\\\dml\\\\1.2\\\\dml-builtins.dml"
                    }
                    #line 1171 "C:\\\\Users\\\\nagen\\\\simics-projects\\\\my-intel-simics-project-1\\\\win64\\\\bin\\\\dml\\\\1.2\\\\dml-builtins.dml"
                    v279_value = v283_value;
                    #line 1455 "C:\\\\Users\\\\nagen\\\\simics-projects\\\\my-intel-simics-project-1\\\\win64\\\\bin\\\\dml\\\\1.2\\\\dml-builtins.dml"
                }
                #line 1459 "C:\\\\Users\\\\nagen\\\\simics-projects\\\\my-intel-simics-project-1\\\\win64\\\\bin\\\\dml\\\\1.2\\\\dml-builtins.dml"
                SIM_LOG_INFO(4, _dev->regs._obj, Register_Read, "%s from register regs.r[%u] (addr %#llx) -> 0x%0*llx", SIM_get_mem_op_inquiry(v279_memop) ? "Inquiry read" : "Read", (uint32 )(_idx0), (uint64 )SIM_get_mem_op_physical_address(v279_memop), 8, (uint64 )v279_value);
                #line 1425 "C:\\\\Users\\\\nagen\\\\simics-projects\\\\my-intel-simics-project-1\\\\win64\\\\bin\\\\dml\\\\1.2\\\\dml-builtins.dml"
                v271_value = v279_value;
                #line 1420 "C:\\\\Users\\\\nagen\\\\simics-projects\\\\my-intel-simics-project-1\\\\win64\\\\bin\\\\dml\\\\1.2\\\\dml-builtins.dml"
            }
            #line 1422 "C:\\\\Users\\\\nagen\\\\simics-projects\\\\my-intel-simics-project-1\\\\win64\\\\bin\\\\dml\\\\1.2\\\\dml-builtins.dml"
        }
        #line 1408 "C:\\\\Users\\\\nagen\\\\simics-projects\\\\my-intel-simics-project-1\\\\win64\\\\bin\\\\dml\\\\1.2\\\\dml-builtins.dml"
        v269_value = v271_value;
        #line 1405 "C:\\\\Users\\\\nagen\\\\simics-projects\\\\my-intel-simics-project-1\\\\win64\\\\bin\\\\dml\\\\1.2\\\\dml-builtins.dml"
    }
    *value = v269_value;
    #line 1406 "C:\\\\Users\\\\nagen\\\\simics-projects\\\\my-intel-simics-project-1\\\\win64\\\\bin\\\\dml\\\\1.2\\\\dml-builtins.dml"
    return 0;
    #line 1406 "C:\\\\Users\\\\nagen\\\\simics-projects\\\\my-intel-simics-project-1\\\\win64\\\\bin\\\\dml\\\\1.2\\\\dml-builtins.dml"
}
#line 158 "C:\\Users\\nagen\\simics-projects\\my-intel-simics-project-1\\logs\\test\\win64\\modules\\dmlc\\test\\scratch\\split\\T_split-87.c"

