/*
 * Generated by dmlc, do not edit!
 *
 * Source files:
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\modules\dmlc\test\1.2\misc\T_split_output.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\modules\dmlc\test\1.2\testing.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\1.2\dml-builtins.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\simulator\python.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\base\attr-value.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\util\alloc.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\module-host-config.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\util\help-macros.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\util\strbuf.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\base-types.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\host-info.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\build-id.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\build-id-7.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\base\version.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\base\types.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\processor\event.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\processor\time.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\base\event.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\base\time.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\base\conf-object.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\util\vect.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\base\sobject.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\util\hashtab.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\model-iface\register-view.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\pywrap.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\model-iface\int-register.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\model-iface\bank-instrumentation.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\model-iface\instrumentation-provider.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\base\memory-transaction.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\base\memory.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\devs\io-memory.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\1.2\simics-api.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\util\bitcount.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\1.2\simics-processor.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\1.2\simics-memory.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\1.2\simics-hindsight.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\1.2\simics-event.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\1.2\simics-device.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\1.2\simics-configuration.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\1.2\simics-breakpoints.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\1.2\simics-types.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\device-api.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\obsolete\6.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\processor\generic-spr.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\model-iface\breakpoints.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\util\int128.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\util\arith.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\base\cbdata.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\base\breakpoints.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\processor\types.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\util\dbuffer.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\base\sim-exception.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\base\object-locks.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\base\notifier.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\base\map-target.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\base\direct-memory.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\base\transaction.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\base\hap-producer.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\base\global-notifier.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\base\configuration.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\base\log.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\base\clock.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\model-iface\cycle.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\base\local-time.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\base\bigtime.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\base\duration.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\base\callbacks.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\util\frags.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\util\swabber.dml
 */

#ifndef SIMICS_6_API
#define SIMICS_6_API
#endif

#include "T_split.h"
#include "T_split-protos.c"
void
 test_notify_state_change(test_t *dev)
{
    if (!dev->_issuing_state_callbacks) {
        dev->_issuing_state_callbacks = true;
        SIM_notify(&dev->obj, Sim_Notify_State_Change);
        dev->_issuing_state_callbacks = false;
    }
}
// DML notification registration callback
void _test_update_has_state_notifier(conf_object_t *_obj, notifier_type_t type, bool has_subscribers)
{
    if (type == Sim_Notify_State_Change) {
        test_t *_dev = (test_t*)_obj;
        _dev->_has_state_callbacks = has_subscribers;
    }
}

conf_object_t *
test_alloc(conf_class_t *cls)
{
    test_t *_dev = MM_ZALLOC(1, test_t);
    _dev->_immediate_after_state = MM_ZALLOC(1, _dml_immediate_after_state_t);
    return &_dev->obj;
}

lang_void *
test_init(conf_object_t *_obj)
{
    test_t *_dev = (test_t*)_obj;
    _init_port_objs(_dev);
    _init_static_vars(_dev);
    _init_data_objs(_dev);
    ht_init_int_table(&(_dev->_subsequent_log_ht));
    QINIT(_dev->_immediate_after_state->queue);
    if (_DML_M_init(_dev))
    return 0;
    if (_DML_M_hard_reset(_dev))
    return 0;
    SIM_add_notifier(_obj, Sim_Notify_Object_Delete, _obj, test_pre_delete, NULL);
    return _obj;
}

void test_finalize(conf_object_t *_obj)
{
    test_t *_dev UNUSED = (test_t *)_obj;
}

void test_objects_finalized(conf_object_t *_obj)
{
    test_t *_dev UNUSED = (test_t *)_obj;
    _dev->_immediate_after_state->warn_upon_deletion = true;
    _DML_execute_immediate_afters_now(_obj, _dev->_immediate_after_state);
}

void test_pre_delete(conf_object_t *_subscriber, conf_object_t *_obj, lang_void *_data)
{
    test_t *_dev = (test_t *)_obj;
    _DML_pre_delete_cancel_immediate_afters(_obj, _dev->_immediate_after_state);
    #line 1954 "C:\\\\Users\\\\nagen\\\\simics-projects\\\\my-intel-simics-project-1\\\\win64\\\\bin\\\\dml\\\\1.2\\\\dml-builtins.dml"
    if (!(SIM_object_clock(&_dev->obj) != NULL))
    #line 1954 "C:\\\\Users\\\\nagen\\\\simics-projects\\\\my-intel-simics-project-1\\\\win64\\\\bin\\\\dml\\\\1.2\\\\dml-builtins.dml"
    {
        #line 1957 "C:\\\\Users\\\\nagen\\\\simics-projects\\\\my-intel-simics-project-1\\\\win64\\\\bin\\\\dml\\\\1.2\\\\dml-builtins.dml"
    }
    #line 1957 "C:\\\\Users\\\\nagen\\\\simics-projects\\\\my-intel-simics-project-1\\\\win64\\\\bin\\\\dml\\\\1.2\\\\dml-builtins.dml"
    else
    #line 1962 "C:\\\\Users\\\\nagen\\\\simics-projects\\\\my-intel-simics-project-1\\\\win64\\\\bin\\\\dml\\\\1.2\\\\dml-builtins.dml"
    SIM_event_cancel_time(&_dev->obj, _send_now_evclass_3, &_dev->obj, NULL, NULL);
    #line 152 "C:\\Users\\nagen\\simics-projects\\my-intel-simics-project-1\\logs\\test\\win64\\modules\\dmlc\\test\\scratch\\split\\T_split-56.c"
    if (SIM_object_clock(_obj)) {
        _cancel_simple_delay_events(_obj, SIM_object_clock(_obj), NULL);
        _cancel_simple_delay_events(_obj, SIM_picosecond_clock(_obj), NULL);
    }
    test_deinit(_obj);
}

void test_deinit(conf_object_t *_obj)
{
    test_t *_dev UNUSED = (test_t *)_obj;
    _DML_execute_immediate_afters_now(_obj, _dev->_immediate_after_state);
    _free_table(&_dev->_subsequent_log_ht);
    QFREE(_dev->_immediate_after_state->queue);
    if (likely(!_dev->_immediate_after_state->posted)) {
        MM_FREE(_dev->_immediate_after_state);
    } else {
        _dev->_immediate_after_state->deleted = true;
    }
}

