/* Generated by dmlc, do not edit! */

#ifndef T_LARGE_STRUCT_STRUCT_H
#define T_LARGE_STRUCT_STRUCT_H

typedef struct test test_t;

conf_class_t *_initialize_T_large_struct(void);


#endif /* not T_LARGE_STRUCT_STRUCT_H */
