/*
 * Generated by dmlc, do not edit!
 *
 * Source files:
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\modules\dmlc\test\1.2\methods\T_inline_event.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\modules\dmlc\test\1.2\testing.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\1.2\dml-builtins.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\simulator\python.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\base\attr-value.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\util\alloc.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\module-host-config.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\util\help-macros.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\util\strbuf.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\base-types.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\host-info.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\build-id.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\build-id-7.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\base\version.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\base\types.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\processor\event.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\processor\time.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\base\event.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\base\time.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\base\conf-object.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\util\vect.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\base\sobject.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\util\hashtab.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\model-iface\register-view.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\pywrap.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\model-iface\int-register.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\model-iface\bank-instrumentation.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\model-iface\instrumentation-provider.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\base\memory-transaction.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\base\memory.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\devs\io-memory.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\1.2\simics-api.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\util\bitcount.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\1.2\simics-processor.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\1.2\simics-memory.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\1.2\simics-hindsight.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\1.2\simics-event.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\1.2\simics-device.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\1.2\simics-configuration.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\1.2\simics-breakpoints.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\1.2\simics-types.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\device-api.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\obsolete\6.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\processor\generic-spr.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\model-iface\breakpoints.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\util\int128.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\util\arith.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\base\cbdata.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\base\breakpoints.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\processor\types.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\util\dbuffer.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\base\sim-exception.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\base\object-locks.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\base\notifier.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\base\map-target.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\base\direct-memory.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\base\transaction.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\base\hap-producer.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\base\global-notifier.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\base\configuration.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\base\log.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\base\clock.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\model-iface\cycle.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\base\local-time.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\base\bigtime.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\base\duration.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\base\callbacks.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\util\frags.dml
 *   C:\Users\nagen\simics-projects\my-intel-simics-project-1\win64\bin\dml\api\6\1.2\simics\util\swabber.dml
 */

#ifndef SIMICS_6_API
#define SIMICS_6_API
#endif

#include "T_inline_event.h"
#include "T_inline_event-protos.c"

static attr_value_t get_runtest(conf_object_t *_obj, lang_void *_aux)
{
    test_t *_dev UNUSED = (test_t*)_obj;
    attr_value_t _val0;
    attr_value_t v3_value UNUSED ;
    memset((void *)&v3_value, 0, sizeof(attr_value_t ));
    #line 311 "C:\\\\Users\\\\nagen\\\\simics-projects\\\\my-intel-simics-project-1\\\\win64\\\\bin\\\\dml\\\\1.2\\\\dml-builtins.dml"
    {
        #line 386 "C:\\\\Users\\\\nagen\\\\simics-projects\\\\my-intel-simics-project-1\\\\win64\\\\bin\\\\dml\\\\1.2\\\\dml-builtins.dml"
        attr_value_t v6_value UNUSED ;
        #line 386 "C:\\\\Users\\\\nagen\\\\simics-projects\\\\my-intel-simics-project-1\\\\win64\\\\bin\\\\dml\\\\1.2\\\\dml-builtins.dml"
        memset((void *)&v6_value, 0, sizeof(attr_value_t ));
        {
            #line 21 "C:\\\\Users\\\\nagen\\\\simics-projects\\\\my-intel-simics-project-1\\\\modules\\\\dmlc\\\\test\\\\1.2\\\\testing.dml"
            attr_value_t v8_value UNUSED ;
            #line 21 "C:\\\\Users\\\\nagen\\\\simics-projects\\\\my-intel-simics-project-1\\\\modules\\\\dmlc\\\\test\\\\1.2\\\\testing.dml"
            memset((void *)&v8_value, 0, sizeof(attr_value_t ));
            #line 21 "C:\\\\Users\\\\nagen\\\\simics-projects\\\\my-intel-simics-project-1\\\\modules\\\\dmlc\\\\test\\\\1.2\\\\testing.dml"
            {
                bool v9_result UNUSED  = 1;
                {
                    #line 19 "C:\\\\Users\\\\nagen\\\\simics-projects\\\\my-intel-simics-project-1\\\\modules\\\\dmlc\\\\test\\\\1.2\\\\methods\\\\T_inline_event.dml"
                    bool v10_ok UNUSED  = 0;
                    #line 21 "C:\\\\Users\\\\nagen\\\\simics-projects\\\\my-intel-simics-project-1\\\\modules\\\\dmlc\\\\test\\\\1.2\\\\methods\\\\T_inline_event.dml"
                    {
                        #line 21 "C:\\\\Users\\\\nagen\\\\simics-projects\\\\my-intel-simics-project-1\\\\modules\\\\dmlc\\\\test\\\\1.2\\\\methods\\\\T_inline_event.dml"
                        void  *v12_param UNUSED  = NULL;
                        #line 15 "C:\\\\Users\\\\nagen\\\\simics-projects\\\\my-intel-simics-project-1\\\\modules\\\\dmlc\\\\test\\\\1.2\\\\methods\\\\T_inline_event.dml"
                        SIM_LOG_INFO(1, &_dev->obj, 0, "CALLBACK");
                        #line 21 "C:\\\\Users\\\\nagen\\\\simics-projects\\\\my-intel-simics-project-1\\\\modules\\\\dmlc\\\\test\\\\1.2\\\\methods\\\\T_inline_event.dml"
                    }
                    #line 23 "C:\\\\Users\\\\nagen\\\\simics-projects\\\\my-intel-simics-project-1\\\\modules\\\\dmlc\\\\test\\\\1.2\\\\methods\\\\T_inline_event.dml"
                    v10_ok = 1;
                    #line 19 "C:\\\\Users\\\\nagen\\\\simics-projects\\\\my-intel-simics-project-1\\\\modules\\\\dmlc\\\\test\\\\1.2\\\\methods\\\\T_inline_event.dml"
                    v9_result = v10_ok;
                    #line 23 "C:\\\\Users\\\\nagen\\\\simics-projects\\\\my-intel-simics-project-1\\\\modules\\\\dmlc\\\\test\\\\1.2\\\\testing.dml"
                }
                v8_value = SIM_make_attr_boolean(v9_result);
            }
            #line 21 "C:\\\\Users\\\\nagen\\\\simics-projects\\\\my-intel-simics-project-1\\\\modules\\\\dmlc\\\\test\\\\1.2\\\\testing.dml"
            v6_value = v8_value;
            #line 387 "C:\\\\Users\\\\nagen\\\\simics-projects\\\\my-intel-simics-project-1\\\\win64\\\\bin\\\\dml\\\\1.2\\\\dml-builtins.dml"
        }
        #line 386 "C:\\\\Users\\\\nagen\\\\simics-projects\\\\my-intel-simics-project-1\\\\win64\\\\bin\\\\dml\\\\1.2\\\\dml-builtins.dml"
        v3_value = v6_value;
        #line 311 "C:\\\\Users\\\\nagen\\\\simics-projects\\\\my-intel-simics-project-1\\\\win64\\\\bin\\\\dml\\\\1.2\\\\dml-builtins.dml"
    }
    #line 131 "C:\\Users\\nagen\\simics-projects\\my-intel-simics-project-1\\logs\\test\\win64\\modules\\dmlc\\test\\scratch\\1.2\\methods\\inline_event\\T_inline_event.c"
    _val0 = v3_value;
    return _val0;
}

static conf_object_t *
test_alloc(conf_class_t *cls)
{
    test_t *_dev = MM_ZALLOC(1, test_t);
    _dev->_immediate_after_state = MM_ZALLOC(1, _dml_immediate_after_state_t);
    return &_dev->obj;
}

static lang_void *
test_init(conf_object_t *_obj)
{
    test_t *_dev = (test_t*)_obj;
    _init_port_objs(_dev);
    _init_static_vars(_dev);
    _init_data_objs(_dev);
    ht_init_int_table(&(_dev->_subsequent_log_ht));
    QINIT(_dev->_immediate_after_state->queue);
    if (_DML_M_init(_dev))
    return 0;
    if (_DML_M_hard_reset(_dev))
    return 0;
    SIM_add_notifier(_obj, Sim_Notify_Object_Delete, _obj, test_pre_delete, NULL);
    return _obj;
}

static void test_finalize(conf_object_t *_obj)
{
    test_t *_dev UNUSED = (test_t *)_obj;
}

static void test_objects_finalized(conf_object_t *_obj)
{
    test_t *_dev UNUSED = (test_t *)_obj;
    _dev->_immediate_after_state->warn_upon_deletion = true;
    _DML_execute_immediate_afters_now(_obj, _dev->_immediate_after_state);
}

static void test_pre_delete(conf_object_t *_subscriber, conf_object_t *_obj, lang_void *_data)
{
    test_t *_dev = (test_t *)_obj;
    _DML_pre_delete_cancel_immediate_afters(_obj, _dev->_immediate_after_state);
    #line 1954 "C:\\\\Users\\\\nagen\\\\simics-projects\\\\my-intel-simics-project-1\\\\win64\\\\bin\\\\dml\\\\1.2\\\\dml-builtins.dml"
    if (!(SIM_object_clock(&_dev->obj) != NULL))
    #line 1954 "C:\\\\Users\\\\nagen\\\\simics-projects\\\\my-intel-simics-project-1\\\\win64\\\\bin\\\\dml\\\\1.2\\\\dml-builtins.dml"
    {
        #line 1957 "C:\\\\Users\\\\nagen\\\\simics-projects\\\\my-intel-simics-project-1\\\\win64\\\\bin\\\\dml\\\\1.2\\\\dml-builtins.dml"
    }
    #line 1957 "C:\\\\Users\\\\nagen\\\\simics-projects\\\\my-intel-simics-project-1\\\\win64\\\\bin\\\\dml\\\\1.2\\\\dml-builtins.dml"
    else
    #line 1962 "C:\\\\Users\\\\nagen\\\\simics-projects\\\\my-intel-simics-project-1\\\\win64\\\\bin\\\\dml\\\\1.2\\\\dml-builtins.dml"
    SIM_event_cancel_time(&_dev->obj, _send_now_evclass_2, &_dev->obj, NULL, NULL);
    #line 187 "C:\\Users\\nagen\\simics-projects\\my-intel-simics-project-1\\logs\\test\\win64\\modules\\dmlc\\test\\scratch\\1.2\\methods\\inline_event\\T_inline_event.c"
    if (SIM_object_clock(_obj)) {
        _cancel_simple_delay_events(_obj, SIM_object_clock(_obj), NULL);
        _cancel_simple_delay_events(_obj, SIM_picosecond_clock(_obj), NULL);
    }
    test_deinit(_obj);
}

static void test_deinit(conf_object_t *_obj)
{
    test_t *_dev UNUSED = (test_t *)_obj;
    _DML_execute_immediate_afters_now(_obj, _dev->_immediate_after_state);
    _free_table(&_dev->_subsequent_log_ht);
    QFREE(_dev->_immediate_after_state->queue);
    if (likely(!_dev->_immediate_after_state->posted)) {
        MM_FREE(_dev->_immediate_after_state);
    } else {
        _dev->_immediate_after_state->deleted = true;
    }
}

static void test_dealloc(conf_object_t *dev)
{
    MM_FREE(dev);
}

static void  _DML_EV_foo__callback(conf_object_t *_obj, void  *param)
{
    test_t *_dev UNUSED = (test_t*)_obj;
    if (_DML_M_foo__callback(_dev, param))
    SIM_LOG_ERROR(&_dev->obj, 0, "Uncaught DML exception");
}

static void  _DML_EV_foo__destroy(conf_object_t *_obj, void  *data)
{
    test_t *_dev UNUSED = (test_t*)_obj;
    if (_DML_M_foo__destroy(_dev, data))
    SIM_LOG_ERROR(&_dev->obj, 0, "Uncaught DML exception");
}

static attr_value_t _DML_EV_foo__get_event_info(conf_object_t *_obj, void  *data)
{
    test_t *_dev UNUSED = (test_t*)_obj;
    attr_value_t info;
    memset((void *)&info, 0, sizeof(attr_value_t ));
    {
        attr_value_t v31__ret_info UNUSED ;
        memset((void *)&v31__ret_info, 0, sizeof(attr_value_t ));
        if (_DML_M_foo__get_event_info(_dev, data, &v31__ret_info))
        SIM_LOG_ERROR(&_dev->obj, 0, "Uncaught DML exception");
        info = v31__ret_info;
    }
    return info;
}

static void  *_DML_EV_foo__set_event_info(conf_object_t *_obj, attr_value_t info)
{
    test_t *_dev UNUSED = (test_t*)_obj;
    void  *data = NULL;
    {
        void  *v32__ret_data UNUSED  = NULL;
        if (_DML_M_foo__set_event_info(_dev, info, &v32__ret_data))
        SIM_LOG_ERROR(&_dev->obj, 0, "Uncaught DML exception");
        data = v32__ret_data;
    }
    return data;
}

static char *_DML_EV_foo__describe_event(conf_object_t *_obj, void  *data)
{
    test_t *_dev UNUSED = (test_t*)_obj;
    char *description = NULL;
    {
        char *v33__ret_description UNUSED  = NULL;
        if (_DML_M_foo__describe_event(_dev, data, &v33__ret_description))
        SIM_LOG_ERROR(&_dev->obj, 0, "Uncaught DML exception");
        description = v33__ret_description;
    }
    return description;
}

static const _id_info_t _id_infos[3] UNUSED = {
    {"dev", NULL, 0, 1},
    {"foo", NULL, 0, 2},
    {"runtest", NULL, 0, 3}
};
static ht_str_table_t _id_info_ht UNUSED = HT_STR_NULL(false);
static void * const _object_vtables[3] UNUSED = {(&_tr__dev__object), (&_tr_foo__object), (&_tr_runtest__object)};
static void _startup_calls(void)
{
}
static void _init_data_objs(test_t *_dev)
{
    #line 274 "C:\\\\Users\\\\nagen\\\\simics-projects\\\\my-intel-simics-project-1\\\\win64\\\\bin\\\\dml\\\\1.2\\\\dml-builtins.dml"
    _dev->_has_state_callbacks = 0;
    #line 282 "C:\\Users\\nagen\\simics-projects\\my-intel-simics-project-1\\logs\\test\\win64\\modules\\dmlc\\test\\scratch\\1.2\\methods\\inline_event\\T_inline_event.c"
    #line 273 "C:\\\\Users\\\\nagen\\\\simics-projects\\\\my-intel-simics-project-1\\\\win64\\\\bin\\\\dml\\\\1.2\\\\dml-builtins.dml"
    _dev->_issuing_state_callbacks = 0;
    #line 285 "C:\\Users\\nagen\\simics-projects\\my-intel-simics-project-1\\logs\\test\\win64\\modules\\dmlc\\test\\scratch\\1.2\\methods\\inline_event\\T_inline_event.c"
}

void
hard_reset_test(test_t *_obj)
{
    test_t *_dev UNUSED = (test_t *)_obj;

    if (_DML_M_hard_reset(_dev))
    SIM_LOG_ERROR(&_dev->obj, 0, "Uncaught DML exception");
}

void
soft_reset_test(test_t *_obj)
{
    test_t *_dev UNUSED = (test_t *)_obj;

    if (_DML_M_soft_reset(_dev))
    SIM_LOG_ERROR(&_dev->obj, 0, "Uncaught DML exception");
}

/* init */
static bool _DML_M_init(test_t *_dev)
#line 247 "C:\\\\Users\\\\nagen\\\\simics-projects\\\\my-intel-simics-project-1\\\\win64\\\\bin\\\\dml\\\\1.2\\\\dml-builtins.dml"
{
    #line 251 "C:\\\\Users\\\\nagen\\\\simics-projects\\\\my-intel-simics-project-1\\\\win64\\\\bin\\\\dml\\\\1.2\\\\dml-builtins.dml"
    return 0;
    #line 251 "C:\\\\Users\\\\nagen\\\\simics-projects\\\\my-intel-simics-project-1\\\\win64\\\\bin\\\\dml\\\\1.2\\\\dml-builtins.dml"
}
#line 314 "C:\\Users\\nagen\\simics-projects\\my-intel-simics-project-1\\logs\\test\\win64\\modules\\dmlc\\test\\scratch\\1.2\\methods\\inline_event\\T_inline_event.c"

/* foo.set_event_info */
static bool _DML_M_foo__set_event_info(test_t *_dev, attr_value_t info, void  **data)
#line 1830 "C:\\\\Users\\\\nagen\\\\simics-projects\\\\my-intel-simics-project-1\\\\win64\\\\bin\\\\dml\\\\1.2\\\\dml-builtins.dml"
{
    #line 1830 "C:\\\\Users\\\\nagen\\\\simics-projects\\\\my-intel-simics-project-1\\\\win64\\\\bin\\\\dml\\\\1.2\\\\dml-builtins.dml"
    void  *v38_data UNUSED  = NULL;
    if (!SIM_attr_is_nil(info))
    SIM_LOG_ERROR(&_dev->obj, 0, "Strange event info");
    #line 1834 "C:\\\\Users\\\\nagen\\\\simics-projects\\\\my-intel-simics-project-1\\\\win64\\\\bin\\\\dml\\\\1.2\\\\dml-builtins.dml"
    v38_data = NULL;
    *data = v38_data;
    #line 1835 "C:\\\\Users\\\\nagen\\\\simics-projects\\\\my-intel-simics-project-1\\\\win64\\\\bin\\\\dml\\\\1.2\\\\dml-builtins.dml"
    return 0;
    #line 1835 "C:\\\\Users\\\\nagen\\\\simics-projects\\\\my-intel-simics-project-1\\\\win64\\\\bin\\\\dml\\\\1.2\\\\dml-builtins.dml"
}
#line 331 "C:\\Users\\nagen\\simics-projects\\my-intel-simics-project-1\\logs\\test\\win64\\modules\\dmlc\\test\\scratch\\1.2\\methods\\inline_event\\T_inline_event.c"

/* foo.get_event_info */
static bool _DML_M_foo__get_event_info(test_t *_dev, void  *data, attr_value_t *info)
#line 1822 "C:\\\\Users\\\\nagen\\\\simics-projects\\\\my-intel-simics-project-1\\\\win64\\\\bin\\\\dml\\\\1.2\\\\dml-builtins.dml"
{
    #line 1822 "C:\\\\Users\\\\nagen\\\\simics-projects\\\\my-intel-simics-project-1\\\\win64\\\\bin\\\\dml\\\\1.2\\\\dml-builtins.dml"
    attr_value_t v41_info UNUSED ;
    #line 1822 "C:\\\\Users\\\\nagen\\\\simics-projects\\\\my-intel-simics-project-1\\\\win64\\\\bin\\\\dml\\\\1.2\\\\dml-builtins.dml"
    memset((void *)&v41_info, 0, sizeof(attr_value_t ));
    if (data != (NULL))
    SIM_LOG_ERROR(&_dev->obj, 0, "foo.get_event_info(): Don't know how to handle non-NULL event data");
    #line 1827 "C:\\\\Users\\\\nagen\\\\simics-projects\\\\my-intel-simics-project-1\\\\win64\\\\bin\\\\dml\\\\1.2\\\\dml-builtins.dml"
    v41_info = SIM_make_attr_nil();
    *info = v41_info;
    #line 1828 "C:\\\\Users\\\\nagen\\\\simics-projects\\\\my-intel-simics-project-1\\\\win64\\\\bin\\\\dml\\\\1.2\\\\dml-builtins.dml"
    return 0;
    #line 1828 "C:\\\\Users\\\\nagen\\\\simics-projects\\\\my-intel-simics-project-1\\\\win64\\\\bin\\\\dml\\\\1.2\\\\dml-builtins.dml"
}
#line 350 "C:\\Users\\nagen\\simics-projects\\my-intel-simics-project-1\\logs\\test\\win64\\modules\\dmlc\\test\\scratch\\1.2\\methods\\inline_event\\T_inline_event.c"

/* foo.destroy */
static bool _DML_M_foo__destroy(test_t *_dev, void  *data)
#line 1837 "C:\\\\Users\\\\nagen\\\\simics-projects\\\\my-intel-simics-project-1\\\\win64\\\\bin\\\\dml\\\\1.2\\\\dml-builtins.dml"
{
    return 0;
    #line 1838 "C:\\\\Users\\\\nagen\\\\simics-projects\\\\my-intel-simics-project-1\\\\win64\\\\bin\\\\dml\\\\1.2\\\\dml-builtins.dml"
}
#line 359 "C:\\Users\\nagen\\simics-projects\\my-intel-simics-project-1\\logs\\test\\win64\\modules\\dmlc\\test\\scratch\\1.2\\methods\\inline_event\\T_inline_event.c"

/* foo.describe_event */
static bool _DML_M_foo__describe_event(test_t *_dev, void  *data, char **description)
#line 1815 "C:\\\\Users\\\\nagen\\\\simics-projects\\\\my-intel-simics-project-1\\\\win64\\\\bin\\\\dml\\\\1.2\\\\dml-builtins.dml"
{
    #line 1815 "C:\\\\Users\\\\nagen\\\\simics-projects\\\\my-intel-simics-project-1\\\\win64\\\\bin\\\\dml\\\\1.2\\\\dml-builtins.dml"
    char *v45_description UNUSED  = NULL;
    #line 1819 "C:\\\\Users\\\\nagen\\\\simics-projects\\\\my-intel-simics-project-1\\\\win64\\\\bin\\\\dml\\\\1.2\\\\dml-builtins.dml"
    v45_description = MM_STRDUP("foo");
    *description = v45_description;
    #line 1820 "C:\\\\Users\\\\nagen\\\\simics-projects\\\\my-intel-simics-project-1\\\\win64\\\\bin\\\\dml\\\\1.2\\\\dml-builtins.dml"
    return 0;
    #line 1820 "C:\\\\Users\\\\nagen\\\\simics-projects\\\\my-intel-simics-project-1\\\\win64\\\\bin\\\\dml\\\\1.2\\\\dml-builtins.dml"
}
#line 374 "C:\\Users\\nagen\\simics-projects\\my-intel-simics-project-1\\logs\\test\\win64\\modules\\dmlc\\test\\scratch\\1.2\\methods\\inline_event\\T_inline_event.c"

/* foo.callback */
static bool _DML_M_foo__callback(test_t *_dev, void  *param)
#line 1969 "C:\\\\Users\\\\nagen\\\\simics-projects\\\\my-intel-simics-project-1\\\\win64\\\\bin\\\\dml\\\\1.2\\\\dml-builtins.dml"
{
    #line 15 "C:\\\\Users\\\\nagen\\\\simics-projects\\\\my-intel-simics-project-1\\\\modules\\\\dmlc\\\\test\\\\1.2\\\\methods\\\\T_inline_event.dml"
    SIM_LOG_INFO(1, &_dev->obj, 0, "CALLBACK");
    #line 1982 "C:\\\\Users\\\\nagen\\\\simics-projects\\\\my-intel-simics-project-1\\\\win64\\\\bin\\\\dml\\\\1.2\\\\dml-builtins.dml"
    return 0;
    #line 1982 "C:\\\\Users\\\\nagen\\\\simics-projects\\\\my-intel-simics-project-1\\\\win64\\\\bin\\\\dml\\\\1.2\\\\dml-builtins.dml"
}
#line 386 "C:\\Users\\nagen\\simics-projects\\my-intel-simics-project-1\\logs\\test\\win64\\modules\\dmlc\\test\\scratch\\1.2\\methods\\inline_event\\T_inline_event.c"

/* soft_reset */
static bool _DML_M_soft_reset(test_t *_dev)
#line 1216 "C:\\\\Users\\\\nagen\\\\simics-projects\\\\my-intel-simics-project-1\\\\win64\\\\bin\\\\dml\\\\1.2\\\\dml-builtins.dml"
{
    #line 1218 "C:\\\\Users\\\\nagen\\\\simics-projects\\\\my-intel-simics-project-1\\\\win64\\\\bin\\\\dml\\\\1.2\\\\dml-builtins.dml"
    return 0;
    #line 1218 "C:\\\\Users\\\\nagen\\\\simics-projects\\\\my-intel-simics-project-1\\\\win64\\\\bin\\\\dml\\\\1.2\\\\dml-builtins.dml"
}
#line 396 "C:\\Users\\nagen\\simics-projects\\my-intel-simics-project-1\\logs\\test\\win64\\modules\\dmlc\\test\\scratch\\1.2\\methods\\inline_event\\T_inline_event.c"

/* hard_reset */
static bool _DML_M_hard_reset(test_t *_dev)
#line 1211 "C:\\\\Users\\\\nagen\\\\simics-projects\\\\my-intel-simics-project-1\\\\win64\\\\bin\\\\dml\\\\1.2\\\\dml-builtins.dml"
{
    #line 1213 "C:\\\\Users\\\\nagen\\\\simics-projects\\\\my-intel-simics-project-1\\\\win64\\\\bin\\\\dml\\\\1.2\\\\dml-builtins.dml"
    return 0;
    #line 1213 "C:\\\\Users\\\\nagen\\\\simics-projects\\\\my-intel-simics-project-1\\\\win64\\\\bin\\\\dml\\\\1.2\\\\dml-builtins.dml"
}
#line 406 "C:\\Users\\nagen\\simics-projects\\my-intel-simics-project-1\\logs\\test\\win64\\modules\\dmlc\\test\\scratch\\1.2\\methods\\inline_event\\T_inline_event.c"

conf_class_t *
_initialize_T_inline_event(void)
{

    const class_info_t funcs = {
        .alloc = test_alloc,
        .init = test_init,
        .finalize = test_finalize,
        .objects_finalized = test_objects_finalized,
        .dealloc = test_dealloc,
        .description = "test device",
    };

    conf_class_t *class = SIM_create_class("test", &funcs);
    _dev_class = class;
    if (SIM_clear_exception() != SimExc_No_Exception) {
        fprintf(stderr, "Failed to register class test: %s\n", SIM_last_error());
        return NULL;
    }

    _initialize_traits();
    _initialize_identity_ht();
    _initialize_vtable_hts();
    _initialize_typeseq_after_on_hook_hts();
    _register_events(class);
    _DML_register_attribute(class, "runtest", get_runtest, NULL, 0, NULL, Sim_Attr_Pseudo|Sim_Attr_Internal, "b", "Undocumented");

    const char *const log_groups[] = {
        "Register_Read",
        "Register_Write",
        NULL
    };
    SIM_log_register_groups(class, log_groups);

    _startup_calls();
    return class;
}

static void _initialize_vtable_hts(void)
{
}
static void __attribute__((optimize("O0")))
_tinit_object(struct _object *_ret)
{
}
static void __attribute__((optimize("O0"))) _initialize_traits0(void)
{
    _tinit_object(&_tr__dev__object);
    _tinit_object(&_tr_foo__object);
    _tinit_object(&_tr_runtest__object);
}
static void __attribute__((optimize("O0"))) _initialize_traits(void)
{
    _initialize_traits0();
}
static const _vtable_list_t *const _each__object UNUSED = NULL;
static void _initialize_typeseq_after_on_hook_hts(void)
{
}
static attr_value_t _simple_event_only_domains_get_value(conf_object_t *_obj, lang_void *data)
{
    return _serialize_simple_event_data(0, NULL, _id_infos, (_simple_event_data_t *)data);
}

static lang_void *_simple_event_only_domains_set_value(conf_object_t *_obj, attr_value_t val)
{
    _simple_event_data_t *out;
    set_error_t error = _deserialize_simple_event_data(NULL, 0, 0, NULL, &_id_info_ht, val, &out);
    if (error != Sim_Set_Ok) {
        out = NULL;
    }
    return out;
}

static void _cancel_simple_delay_events(conf_object_t *_obj, conf_object_t *_clock, const _identity_t *_domain)
{
    int (*_pred)(lang_void *, lang_void *) UNUSED = _domain ? _simple_event_predicate : NULL;
}
static void _cancel_simple_events(conf_object_t *_obj, _identity_t _domain)
{
    test_t *_dev UNUSED = (test_t*)_obj;
    if (!SIM_marked_for_deletion(_obj) && SIM_object_clock(_obj)) {
        _cancel_simple_delay_events(_obj, SIM_object_clock(_obj), &_domain);
        _cancel_simple_delay_events(_obj, SIM_picosecond_clock(_obj), &_domain);
    }
    _DML_cancel_afters_in_detached_hook_queues(_dev->_detached_hook_queue_stack, _domain);
}

static void _initialize_identity_ht(void)
{
    ht_insert_str(&_id_info_ht, "test", &_id_infos[0]);
    for (uint64 i = 0; i < 3; ++i) {
        ht_insert_str(&_id_info_ht, _id_infos[i].logname, &_id_infos[i]);
    }
}
static void _register_events(conf_class_t *class)
{
    _send_now_evclass_2 = SIM_register_event("foo", class, 0, _DML_EV_foo__callback, _DML_EV_foo__destroy, _DML_EV_foo__get_event_info, _DML_EV_foo__set_event_info, _DML_EV_foo__describe_event);
}

static void _init_port_objs(test_t *_dev)
{
}
static void _init_static_vars(test_t *_dev)
{
}

// DML serialization functions
static UNUSED bool hard_reset(test_t *_dev)
{
    return _DML_M_hard_reset(_dev);
}
static UNUSED bool soft_reset(test_t *_dev)
{
    return _DML_M_soft_reset(_dev);
}
static UNUSED bool foo__callback(test_t *_dev, void  *param)
{
    return _DML_M_foo__callback(_dev, param);
}
static UNUSED bool foo__describe_event(test_t *_dev, void  *data, char **description)
{
    return _DML_M_foo__describe_event(_dev, data, description);
}
static UNUSED bool foo__destroy(test_t *_dev, void  *data)
{
    return _DML_M_foo__destroy(_dev, data);
}
static UNUSED bool foo__get_event_info(test_t *_dev, void  *data, attr_value_t *info)
{
    return _DML_M_foo__get_event_info(_dev, data, info);
}
static UNUSED bool foo__set_event_info(test_t *_dev, attr_value_t info, void  **data)
{
    return _DML_M_foo__set_event_info(_dev, info, data);
}

