/* Generated by dmlc, do not edit! */

#ifndef T_LARGEOFFSET_STRUCT_H
#define T_LARGEOFFSET_STRUCT_H

typedef struct test test_t;

conf_class_t *_initialize_T_largeoffset(void);


#endif /* not T_LARGEOFFSET_STRUCT_H */
