/* Generated by dmlc, do not edit! */

#ifndef T_TEMPLATE_2_STRUCT_H
#define T_TEMPLATE_2_STRUCT_H

typedef struct test test_t;

conf_class_t *_initialize_T_template_2(void);


#endif /* not T_TEMPLATE_2_STRUCT_H */
