/* Generated by dmlc, do not edit! */

#ifndef T_API_DML_1_4_API_6_STRUCT_H
#define T_API_DML_1_4_API_6_STRUCT_H

typedef struct test test_t;

conf_class_t *_initialize_T_api_dml_1_4_api_6(void);


#endif /* not T_API_DML_1_4_API_6_STRUCT_H */
