/* Generated by dmlc, do not edit! */

#ifndef T_SAVED_DECLARATION_STRUCT_H
#define T_SAVED_DECLARATION_STRUCT_H

typedef struct test test_t;

conf_class_t *_initialize_T_saved_declaration(void);


#endif /* not T_SAVED_DECLARATION_STRUCT_H */
