/* Generated by dmlc, do not edit! */

#ifndef T_SIMPLE_STRUCT_H
#define T_SIMPLE_STRUCT_H

typedef struct test test_t;

conf_class_t *_initialize_T_simple(void);


#endif /* not T_SIMPLE_STRUCT_H */
